Lambda telemetry extension for aws
newrelic/docs-website pull request #10177
Opened 2022-11-04 20:00 UTC by bradleycamacho

Adds a new doc written by @4demos

2022-11-04 20:19 UTC, a-sassman commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +The New Relic AWS Lambda Telemetry extension allows users to send telemetry data straight from their lambda functions into New Relic, with no need to set up triggers or connect Amazon CloudWatch.Send
```suggestion
The New Relic AWS Lambda Telemetry extension allows users to send telemetry data straight from their lambda functions into New Relic, with no need to set up triggers or connect Amazon CloudWatch. Send your logs, events, metrics and traces by simply adding the extension as the layer and inputting your New Relic license key.
```

2022-11-04 20:20 UTC, a-sassman commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +1. In the AWS Console go to **Lambda** > **Functions** then choose the function you'd like to ingest data from.
```suggestion
1. In the AWS Console go to **Lambda** > **Functions** and choose the function you'd like to ingest data from.
```

2022-11-04 20:21 UTC, a-sassman commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +4. Put `arn:aws:lambda:us-west-2:533243300146:layer:python-telemetry-api-extension:<version>` in the field, then click **Add**.
```suggestion
4. Copy and paste `arn:aws:lambda:us-west-2:533243300146:layer:python-telemetry-api-extension:<version>` in the field, then click **Add**.
```

2022-11-04 20:22 UTC, a-sassman commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +5. Go to **configuration**, select **Environment variables** and add **Key: LICENSE_KEY  Value: <var>LICENSE_KEY</var>**.
If it's capitalized in the UI...
```suggestion
5. Go to **Configuration**, select **Environment variables** and add **Key: LICENSE_KEY  Value: <var>LICENSE_KEY</var>**. 
```

2022-11-04 20:23 UTC, a-sassman commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +twelve event types:
Maybe backspace before "twelve" so this isn't on its own line.

2022-11-04 20:23 UTC, a-sassman commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +Traces data are displayed in **Traces** tab. Search for `python-telemetry-api-extension' to filter for these traces.
```suggestion
Trace data are displayed in **Traces** tab. Search for `python-telemetry-api-extension' to filter for these traces.
```

2022-11-04 20:25 UTC, a-sassman reviewed
Looks good! Just a few minor copy edits and suggestions for rewording.

2022-11-04 20:30 UTC, 4demos requested changes

2022-11-04 20:30 UTC, 4demos commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +metaDescription: "New Relic's Amazon App Runner monitoring integration: what data it reports, and how to enable it."
why App Runner? Lambda telemetry extension is another project, nothing common with App Runner

2022-11-04 20:30 UTC, 4demos commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +
add space in "Amazon CloudWatch.Send"

2022-11-04 20:30 UTC, 4demos commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +4. Put `arn:aws:lambda:us-west-2:533243300146:layer:python-telemetry-api-extension:<version>` in the field, then click **Add**.
the name of the function has changed, now it is  `arn:aws:lambda:us-west-2:533243300146:layer:AwsLambdaExtension:<version>`

2022-11-04 20:30 UTC, 4demos commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +
we need to mention that currently set up has to be done in us-west-2 (Oregon) region

2022-11-04 20:30 UTC, 4demos commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +AWS > EXTENSION > python-telemetry-api-extension
AwsLambdaExtension should replace python-telemetry-api-extension

2022-11-04 20:30 UTC, 4demos commented on src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
> +Traces data are displayed in **Traces** tab. Search for `python-telemetry-api-extension' to filter for these traces.
AwsLambdaExtension should replace python-telemetry-api-extension
I's say "to filter for the relevant traces."

2022-11-04 21:33 UTC, 4demos submitted a review, later dismissed

2022-11-08 20:39 UTC, a-sassman approved these changes

2022-11-10 17:02 UTC, merged