feat(snowflake) new content for io
newrelic/docs-website pull request #10293
Opened 2022-11-14 06:55 UTC by akristen

2022-11-15 00:11 UTC, pkosanam requested changes
Requesting to kindly use the below image as a screenshot, as we are about to update the same image on the IO website too 😃

![image](https://user-images.githubusercontent.com/99316285/201794312-ac343f0b-f728-4e71-8d7d-da471b248bf9.png)

2022-11-15 01:12 UTC, pkosanam requested changes

2022-11-15 01:12 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +Once you've installed the Snowflake quickstart, you can see your critical Snowflake data in New Relic.
Once you've installed the [Snowflake quickstart](https://newrelic.com/instant-observability/snowflake), you can see your critical Snowflake data in New Relic.

2022-11-15 01:12 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +
2. Sample queries to execute on NRQL to see list of integrated snowflake metrics
```
SELECT * FROM SnowflakeAccount
```
or
```
SELECT * FROM SnowflakeVirtualWarehouse
```

2022-11-15 10:21 UTC, pkosanam requested changes
Me not being a technical writer, kindly consider my grammatical mistakes if any. 😃

2022-11-15 10:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +        title="Usage by warehouse"
Credit usage by warehouse

2022-11-15 10:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +        id="warehouse-usage"
credit-usage-by-warehouse

2022-11-15 10:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +    2. Designate the file path as `newrelic-snowflake-integrations/queries`.
2. Designate the file path as YOUR_PATH_TO_CLONED_REPOSITORY_DIRECTORY/queries/credit_usage_by_warehouse.sql

2022-11-15 10:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +    3. In `longest_queries.sql`, add the following snippet:
3. In `credit_usage_by_warehouse.sql`, add the following snippet:

2022-11-15 10:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +    4. Add the following snippet to `flex-snowflake.yml`:
4. In the flex-snowflake-linux.yml file present in YOUR_PATH_TO_CLONED_REPOSITORY_DIRECTORY/flexConfigs/, add the following snippet:

2022-11-15 10:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +        - run: <var>YOUR_PATH_TO snowflakeintegration-platform</var> <var>YOUR_PATH_TO config.yaml</var> <var>YOUR_PATH_TO credit_usage_by_warehouse.sql</var>
- run: <var>YOUR_PATH_TO_DOWNLOADED_BINARY_FILE</var> <var> YOUR_PATH_TO_CLONED_REPOSITORY_DIRECTORY/config.yaml</var> <var>YOUR_PATH_TO_CLONED_REPOSITORY_DIRECTORY/queries/credit_usage_by_warehouse.sql</var>

2022-11-16 20:38 UTC, zuluecho9 commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +import infrastructureSnowflakeDashboard from 'images/infrastructure_screenshot-full_snowflake-dashboard.png'
are we missing a screenshot? I see two images in this branch but only one import.

2022-11-16 20:40 UTC, zuluecho9 commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +* Follow our [guided install](https://one.newrelic.com/nr1-core?account=3501165&state=ff641d8b-e722-855e-4c4a-c50c23969dc3) to instrument your system with the infrastructure agent.
we often have very little info about the difference between guided install and regular infra install. not saying you need to work on this now, as i see this in many places. something I sent to paperclypse about this: 

i keep seeing various new docs say 'use our guided install' and link directly to UI. I wonder if we might improve our guided install doc https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/new-relic-guided-install-overview/ and go into more detail about why to use it and what rules/limitations are and instead link to that for more context. I can see many customers being confused around why they'd use guided install and if we send them straight to UI that doesn't really help.

2022-11-16 20:41 UTC, zuluecho9 commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +Once you've installed the [Snowflake quickstart](https://newrelic.com/instant-observability/snowflake), you can see your critical Snowflake data in New Relic.
maybe give a little context for how the quickstart relates to the previous instructions. If we link to it, we should make it more clear they need to follow the link. i tend to do more like 'Next, if you want to x..., then [install the Snowflake quickstart]...'

2022-11-16 20:42 UTC, zuluecho9 commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
> +1. Go to **[one.newrelic.com](https://one.newrelic.com/all-capabilities)**, then click **Metrics & events**.
we could maybe be more clear that these are instructions for after they install the quickstart and want to see the dashboards. at first I thought these were instructions for installing the quickstart.

2022-11-16 21:00 UTC, zuluecho9 approved these changes

2022-11-17 04:31 UTC, merged