Restore style guide docs in taxonomy
newrelic/docs-website pull request #1074
Opened 2021-03-02 00:34 UTC by bradleycamacho

### Tell us why
There were some missing docs in the style guide taxonomy. This PR restores them.

2021-03-02 00:46 UTC, austin-schaefer commented on src/nav/style-guide.yml
> +      - title: Tech writer workflow
This is called `Tech writer workflow` here, but `Tech Writer Workflow` in the actual page frontmatter.

2021-03-02 00:48 UTC, austin-schaefer commented on src/nav/style-guide.yml
> +      - title: Update left navigation pane
Similar teeny nitpick: This is called `left navigation pane` in sidebar but `left-navigation pane` in doc title. The no hyphen version is more correct IMO

2021-03-02 00:50 UTC, austin-schaefer requested changes
Approved, a few minor tweaks/suggestiosn

2021-03-05 20:35 UTC, closed without merging

2021-03-05 20:35 UTC, bradleycamacho commented
Closed since this work has been done in other PRs.