[NR-76990] V6.9.2 release notes, EOL and DG docs update
newrelic/docs-website pull request #10909
Opened 2023-01-04 22:41 UTC by ywang-nr

## Give us some context

* What problems does this PR solve? - Android Agent v6.9.2 doc updates

2023-01-04 22:41 UTC, ywang-nr commented
@cthomas-newrelic for review

2023-01-04 22:54 UTC, homelessbirds commented
@ywang-nr let us know when you're ready for us to review this!

2023-01-06 22:10 UTC, cthomas-newrelic requested changes

2023-01-06 22:10 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-692.mdx
> +* Fixed a bug with the plugin fails to tag and upload 'mapping.txt' file
This statement doesn't accurately describe the problem, but was more a symptom. I'd like to change it to:

"Fixed a bug that allowed direct access to the agent plugin extension's configuration from Kotlin that could result in a failure to tag and upload obfuscation maps."

2023-01-09 15:59 UTC, ywang-nr commented
1/9/2023 Status: Merged Kenny's changes and updated wording

2023-01-10 17:27 UTC, cthomas-newrelic approved these changes
Looks great!

2023-01-10 17:32 UTC, ywang-nr commented
> @ywang-nr let us know when you're ready for us to review this!

@homelessbirds this PR is ready to review by the doc team, target to release this afternoon(1/10/2023)

2023-01-10 19:53 UTC, ywang-nr commented on src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-proguard-or-dexguard-android-apps.mdx
> +              shrinkResources false
do we need it or not?

2023-01-11 00:38 UTC, bradleycamacho approved these changes

2023-01-11 14:47 UTC, merged