Nextcloud io
newrelic/docs-website pull request #10961
Opened 2023-01-09 22:43 UTC by akristen

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

2023-01-09 22:46 UTC, a-sassman commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +You can install the infrastructure agent a few different ways.
```suggestion
You can install the infrastructure agent a few different ways: 
```

2023-01-09 22:52 UTC, a-sassman commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +* Our [guided install](https://one.newrelic.com/nr1-core?state=4f81feab-35f7-e97e-9903-52510f8542bd) is a CLI tool that inspects your system and installs both the infrastructure agent and the best ap
```suggestion
* (Guided install](https://one.newrelic.com/nr1-core?state=4f81feab-35f7-e97e-9903-52510f8542bd): Guided install is a CLI tool that inspects your system and installs both the infrastructure agent and the best application monitoring agent for your system. To learn more about how our guided install works, check out our [overview doc](/docs/infrastructure/host-integrations/installation/new-relic-guided-install-overview). 
* Manual install: If you’d rather install our infrastructure agent manually, you can follow a tutorial for manual installation for [Linux](), [Windows](), or [iOS](). 
```
^Missing links for manual install

2023-01-09 22:52 UTC, a-sassman commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +* If you’d rather install our infrastructure agent manually, you can follow a tutorial for manual installation for [Linux](), [Windows](), or [iOS]().
```suggestion
```

2023-01-09 22:53 UTC, a-sassman commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +5. Complete token authentication. You need to be using Nextcloud 22 or later.
Consider referencing this at the top as a requirement

2023-01-09 22:54 UTC, a-sassman commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +7. To access metrics for Nextcloud, run:
```suggestion
7. To access metrics for Nextcloud, run this command:
```

2023-01-09 22:55 UTC, a-sassman commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +From your browser, go to `http:127.0.0.1:9205/metrics` to view your metrics.
```suggestion
8. From your browser, go to `http:127.0.0.1:9205/metrics` to view your metrics.  
```

2023-01-09 22:56 UTC, a-sassman approved these changes
LGTM other than a few open items.

2023-01-10 01:50 UTC, akristen commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +* If you’d rather install our infrastructure agent manually, you can follow a tutorial for manual installation for [Linux](), [Windows](), or [iOS]().
Fixed!

2023-01-10 02:00 UTC, homelessbirds commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +5. Restart your New Relic infrastructure service by running `sudo systemctl restart newrelic-infra.service`
Do you need a period at the end of this sentece?

2023-01-10 09:21 UTC, pkosanam requested changes

2023-01-10 09:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +6. From your cloned Nextcloud folder, run the following command to initiate username and password authentication:
8. From your cloned Nextcloud folder, run the following command to start and nextcloud using username and password authentication:

NOTE: kindly correct my sentence formation if wrong. 👍

2023-01-10 09:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +
Install our [Prometheus OpenMetrics integration](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-update-or-uninstall-your-prometheus-openmetrics-integration/)

You need to configure the nri-prometheus-config.yml file. Your configuration file should match our snippet in the [nri-prometheus](https://github.com/newrelic/nri-prometheus/blob/main/configs/nri-prometheus-config.yml.sample) repository

2023-01-10 09:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +3. Add that Prometheus OpenMetrics configuration file to `nri-prometheus-config.yml`.
the above points 1, 2 and 3 can be removed

2023-01-10 09:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +4. To get server-related information, replace the URL inside the targets:
To send nextcloud metrics, replace the URL inside the targets with the URL to which the metrics are exposed. Here metrics are exposed on "http://127.0.0.1:9205":

2023-01-10 09:21 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
> +5. Restart your New Relic infrastructure service by running `sudo systemctl restart newrelic-infra.service`
[Restart your New Relic infrastructure service](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/manage-your-agent/start-stop-restart-infrastructure-agent/)

2023-01-11 03:50 UTC, homelessbirds approved these changes
Looks good!

2023-01-11 22:20 UTC, merged