Redmine io
newrelic/docs-website pull request #10974
Opened 2023-01-10 20:12 UTC by akristen

Still a work in progress

2023-01-12 09:03 UTC, pkosanam requested changes

2023-01-12 09:03 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/redmine-integration.mdx
> +
## Get Redmine metrics as a dashboard
Once you've installed the [Redmine quickstart](https://newrelic.com/instant-observability/redmine), you can see your critical Redmine data in New Relic. To find your dashboard in New Relic: Go to [one.newrelic.com](https://one.newrelic.com/all-capabilities) > Dashboards, then select Redmine. You can now query your data. For example:

```
SELECT average(databaseDuration) as 'seconds' from Transaction timeseries
```

2023-01-12 09:50 UTC, homelessbirds approved these changes

2023-01-17 22:50 UTC, homelessbirds approved these changes

2023-01-17 22:53 UTC, merged