fix(LogConfigurations): Update docs for log data partition UI
newrelic/docs-website pull request #11385
Opened 2023-02-04 01:04 UTC by eknuth

Update the existing docs for managing data partitions in the Logs UI. Replaces an existing configuration field and updates screenshots.

2023-02-04 01:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=11385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=11385) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=11385) it.</sub>

2023-02-06 20:34 UTC, akristen commented on src/content/docs/apis/nerdgraph/examples/nerdgraph-data-partition-rules-tutorial.mdx
> +         <i>(deprecated)</i> The matching criteria for this data partition rule. Once the rule is enabled, logs matching this criteria will be routed to the specified data partition.
Is this recently deprecated? Any reason to keep the row?

2023-02-06 20:49 UTC, akristen requested changes
Made some changes + had a question about the deprecated row. Will approve once I hear back from ya! :)

2023-02-07 01:39 UTC, eknuth commented
Thanks for checking it out!

This is the first notice of deprecation. We're going to keep the field around for a bit to allow people to migrate away. 

I'm happy to make that more clear if it would be helpful.

2023-02-07 14:27 UTC, rkbodenner commented on src/content/docs/apis/nerdgraph/examples/nerdgraph-data-partition-rules-tutorial.mdx
> +        specified with `nrql` that cannot be parsed into `matchingCriteria`, this field will be null.
For this:
> specified with `nrql` that cannot be parsed
How about this instead?
> specified with a NRQL `WHERE` clause in the `nrql` field that cannot be parsed

2023-02-07 14:28 UTC, rkbodenner commented on src/content/docs/apis/nerdgraph/examples/nerdgraph-data-partition-rules-tutorial.mdx
> +        The matching criteria for this data partition rule specified using a NRQL `where` clause. Once the rule is enabled, logs matching this criteria will be routed to the specified data partition.
Maybe uppercase that WHERE to distinguish it from the other things we're putting in sans-serif font?

Also consider linking to the NRQL docs: https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/

2023-02-07 18:14 UTC, eknuth commented
@rkbodenner updated

2023-02-13 17:40 UTC, homelessbirds submitted a review, later dismissed

2023-02-15 13:38 UTC, zuluecho9 approved these changes

2023-02-15 16:01 UTC, akristen approved these changes

2023-02-15 16:01 UTC, merged