Move doc tile component
newrelic/docs-website pull request #11511
Opened 2023-02-13 22:11 UTC by LizBaker

This moves the doc tile component out of the index page and adds an optional wrapper for formatting.
passing `numbered` to the wrapper will auto number the tiles, but you can also pass a number to individual tiles (not used in the wrapper) via a `number` prop. there is also a label prop which takes an object with text and a color.

### screenshots
<img width="700" alt="Screen Shot 2023-02-13 at 1 54 29 PM" src="https://user-images.githubusercontent.com/39655074/218585739-49d0d8a2-2363-44b3-9c1b-57f23c849965.png">
<img width="700" alt="Screen Shot 2023-02-13 at 1 54 35 PM" src="https://user-images.githubusercontent.com/39655074/218585612-cd4839fe-132c-47d8-9527-2d844e707e2e.png">
<img width="700" alt="Screen Shot 2023-02-13 at 1 58 45 PM" src="https://user-images.githubusercontent.com/39655074/218585669-5a04df60-ba0b-4187-88df-ca25f12ea748.png">
<img width="700" alt="Screen Shot 2023-02-13 at 1 58 51 PM" src="https://user-images.githubusercontent.com/39655074/218585679-8f5ec9be-cf70-44fa-b302-6972e8464dd3.png">

2023-02-13 22:45 UTC, sunnyzanchi requested changes
looks good! left one comment, and i saw this minor visual bug at <1050px

<img width="1037" alt="Screen Shot 2023-02-13 at 5 34 13 PM" src="https://user-images.githubusercontent.com/14365008/218591238-2ed09bdf-fc53-4217-ae67-dbaec0a7fa05.png">

2023-02-13 22:45 UTC, sunnyzanchi commented on src/components/DocTile.js
> +DocTile.propTypes = {
i think these need to be updated

2023-02-14 00:04 UTC, LizBaker commented
@sunnyzanchi oof there were some silly media queries in there that i don't think we really suffer from removing (the tiles are a bit tighter on the homepage at smaller screen sizes) so i dumped em

2023-02-14 17:49 UTC, sunnyzanchi approved these changes

2023-02-14 17:52 UTC, clarkmcadoo approved these changes

2023-02-14 17:55 UTC, merged