Added one step in install process due to UI changes
newrelic/docs-website pull request #1177
Opened 2021-03-04 20:52 UTC by CherylFrankenfield

### Tell us why

The UI changed and there is a slightly different step-through process for installation. 

### Anything else you'd like to share?

It's likely not necessary, though adding a screenshot of the view may be useful. 

### Are you making a change to site code?

If you're changing site code (rather than the content of a doc), please follow
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/) 
in your commit messages and pull request title.

2021-03-04 23:43 UTC, mmfred requested changes
Hi @CherylFrankenfield I made some edits and left some comments for you to review in my commit. Please take a look. Thank you!

2021-03-04 23:43 UTC, mmfred commented on src/content/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx
> +2. In the **Back-end, front-end, and mobile applications** section, select the **New Relic Browser** tile. When prompted to select the account you want to add this instrumentation to, choose your acc
@CherylFrankenfield - I did some further revising, following along in the UI. Let me know if I went off down a wrong road.

2021-03-04 23:43 UTC, mmfred commented on src/content/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx
> +5. In the **Choose your instrumentation** section, select **Lite**, **Pro**, or **Pro + SPA**. See [features](/docs/browser/new-relic-browser/getting-started/new-relic-browser) for details about each
I'm not sure that the link correctly supports the selections in this section. If you're okay with the changes, but the link is wrong, let's find a better one.

2021-03-08 19:20 UTC, mmfred approved these changes

2021-03-09 11:30 UTC, urbiz-nr commented
Checked locally, looks great! You can merge, @mmfred !

2021-03-10 20:59 UTC, merged