fix(node agent): update our EOL dates
newrelic/docs-website pull request #12016
Opened 2023-03-10 18:52 UTC by jordigh

Added a few recent releases that were missing, removed a few old ones that are out of support, updated a few EOL dates in the middle that seemed to have accidentally gotten the wrong year.

2023-03-10 19:11 UTC, coreyarnold requested changes
top additions and bottom removals look good. middle edits are 👎

2023-03-10 19:11 UTC, coreyarnold commented on src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
> +        2023-12-01
this can't be changed.

2023-03-10 19:11 UTC, coreyarnold commented on src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
> +        2023-11-18
this can't be changed.

2023-03-10 19:11 UTC, coreyarnold commented on src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
> +        2023-11-09
this can't be changed.

2023-03-10 19:11 UTC, coreyarnold commented on src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
> +        2023-10-28
this can't be changed.

2023-03-10 19:11 UTC, coreyarnold commented on src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
> +        2023-10-13
this can't be changed.

2023-03-11 00:09 UTC, rhetoric101 commented
Let's get these comments resolved before the docs team does a review.

2023-03-13 15:32 UTC, jordigh commented
I have updated the changes to remove all versions that had an EOL before the current date.

2023-03-13 16:06 UTC, ally-sassman approved these changes

2023-03-13 16:06 UTC, merged