add persona homepage
newrelic/docs-website pull request #12044
Opened 2023-03-13 22:33 UTC by sunnyzanchi

this is a big PR, but most of it has already been reviewed. you should just need to review my last five commits

everything looks good from 760px on up, but the left sidebar kind of throws a wrench in things — things look not so great with it open at the smallest widths

2023-03-14 18:51 UTC, tabathadelane requested changes
I think our slab click instrumentation AC got overlooked

2023-03-14 19:30 UTC, tabathadelane approved these changes

2023-03-15 21:29 UTC, tabathadelane approved these changes

2023-03-20 17:37 UTC, tabathadelane commented
Had to trigger a cache clear. The build succeeded in Gatsby Cloud and is not syncing here.

2023-03-20 19:12 UTC, LizBaker approved these changes

2023-03-20 19:13 UTC, tabathadelane approved these changes

2023-03-20 19:20 UTC, merged