Ruby agent: error fingerprinting and user tracking
newrelic/docs-website pull request #12048
Opened 2023-03-14 00:30 UTC by fallwith

The noticed errors documentation has been updated to explain how the error inbox related public API methods `set_error_group_callback` (for error fingerprinting) and `set_user_id` (for user tracking) work.

**NOTE** This is a draft PR designed to accompany [Ruby agent #1833](https://github.com/newrelic/newrelic-ruby-agent/pull/1883). Once the Ruby agent PR has been merged and the Ruby agent team has slated the new code for an agent release, we'll have a better idea of when this docs PR needs to be reviewed and merged.

2023-03-14 21:41 UTC, kaylareopelle requested changes

2023-03-14 21:41 UTC, kaylareopelle commented on src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
> +A Proc based callback can be supplied to the agent to dynamically apply a desired [error group](../../../errors-inbox/errors-inbox) to each noticed error. Use the Ruby agent API [`NewRelic::Agent.set
```suggestion
A `Proc` based callback can be supplied to the agent to dynamically apply a desired [error group](../../../errors-inbox/errors-inbox) to each noticed error. Use the Ruby agent API [`NewRelic::Agent.set_error_group_callback`](https://www.rubydoc.info/github/newrelic/newrelic-ruby-agent/NewRelic/Agent#set_error_group_callback-instance_method) to provide the agent with a callback.
```

2023-03-14 21:41 UTC, kaylareopelle commented on src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
> +This API call takes a callback function (must be of type `Proc`) as its only argument. The argument is required. The API call only needs to be made once per New Relic Ruby agent launch, so the call c
```suggestion
This API call takes a callback function (must be of type `Proc`) as its only argument. The argument is required. The API call only needs to be made once per New Relic Ruby agent launch, so the call can be placed in a Rails initializer or whatnot. If subsequent calls to the API are made, the callback function will update to the newest one provided. Here is an example of a callback being defined and passed to the `NewRelic::Agent.set_error_group_callback` API method:
```

2023-03-14 21:41 UTC, kaylareopelle commented on src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
> +The callback proc will be expected to receive exactly one input argument, a hash. The hash contains the following:
```suggestion
The callback proc is expected to receive exactly one input argument, a hash. The hash contains the following:
```

2023-03-14 21:41 UTC, kaylareopelle commented on src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
> +```
```suggestion
```

2023-03-14 21:41 UTC, kaylareopelle commented on src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
> +The callback proc will be expected to return a string representing the desired error group name if one can be determined. If the proc returns a `nil` or empty string (`''`), then the error will recei
```suggestion
The callback proc is expected to return a string representing the desired error group name if one can be determined. If the proc returns a `nil` or empty string (`''`), then the error will receive server-side grouping logic.
```

2023-03-14 21:41 UTC, kaylareopelle commented on src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
> +This API call takes a callback function (must be of type `Proc`) as its only argument. The argument is required. The API call only needs to be made once per New Relic Ruby agent launch, so the call c
```suggestion
This API call takes a callback method (must be of type `Proc`) as its only argument. The argument is required. The API call only needs to be made once per New Relic Ruby agent launch, so the call can be placed in a Rails initializer or whatnot. If subsequent calls to the API are made, they will update the callback to the newest one provided. Here is an example of a callback being defined and passed to the `NewRelic::Agent.set_error_group_callback` API method:
```

2023-03-14 21:41 UTC, kaylareopelle commented on src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
> +This API call takes a single argument of a string representing a unique identifier for an end user. This string can be a UUID, a database id, etc. The argument is required. The API call should be mad
```suggestion
This API call requires a single argument of a string representing a unique identifier for an end user. This string can be a UUID, a database id, etc. The API call should be made at least once per transaction to inform the New Relic Ruby agent of what user ID to associate the transaction with. Then in turn, when the agent notices errors during the lifespan of the transaction, the errors will bear an `enduser.id` agent attribute that holds the user ID value.
```

2023-03-14 22:19 UTC, kaylareopelle commented on src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
> +This API call takes a callback function (must be of type `Proc`) as its only argument. The argument is required. The API call only needs to be made once per New Relic Ruby agent launch, so the call c
```suggestion
This API call takes a callback method (must be of type `Proc`) as its only argument. The argument is required. The API call only needs to be made once per New Relic Ruby agent launch, so the call can be placed in a Rails initializer or whatnot. If subsequent calls to the API are made, the callback method will update to the newest one provided. Here is an example of a callback being defined and passed to the `NewRelic::Agent.set_error_group_callback` API method:
```

2023-03-14 23:04 UTC, fallwith commented on src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
> +This API call takes a callback function (must be of type `Proc`) as its only argument. The argument is required. The API call only needs to be made once per New Relic Ruby agent launch, so the call c
Superceded by [4cc5173](https://github.com/newrelic/docs-website/pull/12048/commits/4cc5173ffe7fefa1c728a2f814d4d6e8882e7058)

2023-03-29 00:07 UTC, fallwith commented
NOTE: This PR should be merged and released in lockstep with https://github.com/newrelic/docs-website/pull/12357

2023-03-29 22:45 UTC, zuluecho9 approved these changes

2023-03-29 23:05 UTC, merged