Fix: Update to match new Okta UI
newrelic/docs-website pull request #12344
Opened 2023-03-28 18:47 UTC by adammarshallNR

Per changes in https://github.com/newrelic/docs-website/blob/develop/src/content/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration.mdx Also added step 7, to indicate where to add users/groups & added step 8, to make steps 6, 7 & 9 in the general SAML SSO instructions easier

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve? - **Okta UI has been changed.  Additionally, where to find required items in Okta for some of the general instructions are not intuitive.**
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc. - **I'm not sure where to add screenshot, but am happy to do so if required**
* If your issue relates to an existing GitHub issue, please link to it.

2023-03-28 18:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=12344) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=12344) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=12344) it.</sub>

2023-03-28 18:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=12344) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=12344) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=12344) it.</sub>

2023-03-28 19:21 UTC, ally-sassman commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
> +       4. Click **Browse app catalog** and search for "New Relic by organization" (not "New Relic by account") and choose that from the results.
```suggestion
       4. Click **Browse app catalog** and search and select "New Relic by organization".
```

2023-03-28 19:21 UTC, ally-sassman commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
> +       7. Open the newly created application in Okta and go to the **Assignments** tab. This is where you can add users and groups for Authentication.
```suggestion
       7. Open the newly created application in Okta and go to the **Assignments** tab. This is where you can add users and groups for authentication.
```

2023-03-28 19:23 UTC, ally-sassman commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
> +       8. From there, go to the **Sign On** tab. Under **Advanced Sign-on Settings**, you will see **Authentication Domain ID**, you will need to edit this field in step 9 of the general instructions
```suggestion
       8. From there, go to the **Sign On** tab. Under **Advanced Sign-on Settings**, you'll see **Authentication Domain ID**, which you'll need to edit this field in Step 9 of the general instructions below. To the right, click **View SAML setup instructions**. Under **Step 7** of these instructions, you can find the URLs required for Steps 6 & 7 in the general instructions below.
```

2023-03-28 19:24 UTC, ghost requested changes
See my suggestions

2023-03-29 17:49 UTC, adammarshallNR commented
Thank you :) will try to remember for my next edit (or reread the style guide ;) )

2023-03-29 18:18 UTC, ally-sassman approved these changes, later dismissed

2023-03-29 18:20 UTC, ally-sassman commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
> +       4. Click **Browse app catalog** and search and select "New Relic by organization".
```suggestion
       4. Click **Browse app catalog**, then search and select "New Relic by organization".
```

2023-03-29 18:33 UTC, merged