fix(new doc for aerospike): created new doc
newrelic/docs-website pull request #12641
Opened 2023-04-17 14:34 UTC by homelessbirds

2023-04-17 16:34 UTC, pkosanam requested changes
Thank you for the PR @homelessbirds ,

Kindly use the below dashboard image

dashboard image: https://github.com/newrelic/newrelic-quickstarts/blob/892f8e1395a843137f7a8afc14e71ee48c04aa52/dashboards/aerospike/aerospike01.png

2023-04-17 16:34 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/aerospike-integration.mdx
> +### Step 1 (optional): Install the infrastructure agent [#infra-install]
This time, this is not an optional step.
```
### Step 1: Install the infrastructure agent [#infra-install]
```

2023-04-17 16:34 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/aerospike-integration.mdx
> +Installing the infrastructure agent is optional, but doing this will get you important metrics about the host where your app is running.
Installing the infrastructure agent will get you important metrics about the host where your app is running.

2023-04-17 16:34 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/aerospike-integration.mdx
> +First, find the prometheus exporter application named `nri-aerospike`. Nri-aerospike is available in the apt-get repository.
The prometheus exporter application named `nri-aerospike` is available on the apt-get repository.

2023-04-17 16:34 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/aerospike-integration.mdx
> +        #       - "process_"
lines 69 to 74 can be removed

2023-04-17 16:34 UTC, pkosanam commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/aerospike-integration.mdx
> +SELECT latest (aerospike_namespace_memory_free_pct)
SELECT latest(aerospike_namespace_memory_free_pct)

2023-04-18 14:59 UTC, akristen submitted a review, later dismissed
Looks good! Left some copy edits.

2023-04-18 15:02 UTC, homelessbirds commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/aerospike-integration.mdx
> +*  You will see that the **Exporter** is installed in the `/var/db/newrelic-infra/newrelic-integrations/bin` directory
fixed

2023-04-18 15:30 UTC, merged