feat: Diagnostics CLI 2.5.0 new features and release notes
newrelic/docs-website pull request #12930
Opened 2023-05-04 20:25 UTC by daffinito

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?

We are releasing a new version of the Diagnostics CLI which includes a new command line flag `-api-key`.  This PR includes the updates to the relevant docs to document the new flag, and the release notes for the new cli version.

* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

2023-05-04 20:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=12930) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=12930) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=12930) it.</sub>

2023-05-08 17:39 UTC, daffinito commented
hi @ally-sassman , this is ready for review now. thank you!

2023-05-08 17:57 UTC, ally-sassman commented on src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/interpret-nrdiag-output.mdx
> +1. Select an app [in the UI](https://one.newrelic.com), then search for **Diagnostics CLI Output**. OR, click this [**Diagnostics CLI Output** permalink](https://onenr.io/0x0jldL3EjW) to go directly
```suggestion
1. Select an app [in the UI](https://one.newrelic.com), then search for **Diagnostics CLI Output**.
```
I feel like we should offer only one method to get to a page, even if there are other ways to get there. This method allows them to first pick their relevant app, vs. the option which is unclear which app it opens with.

2023-05-08 17:58 UTC, ally-sassman commented on src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag.mdx
> +        Include a file or directory (including subdirectories) in the `nrdiag-output.zip`. Limit 4GB. To upload the results to New Relic also use the `-a` or `-api-key` flag.
```suggestion
        Include a file or directory (including subdirectories) in the `nrdiag-output.zip`. Limit 4GB. Use the `-a` or `-api-key` flag to upload the results to New Relic.
```

2023-05-08 17:58 UTC, ally-sassman commented on src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx
> +  If your system is configured to **not** connect to external IP addresses, this method will not work. Instead, attach the [output files](/docs/using-new-relic/cross-product-functions/diagnostics-cli
```suggestion
  If your system is **not** configured to connect to external IP addresses, this method will not work. Instead, attach the [output files](/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/interpret-nrdiag-output) in an email to New Relic Support.
```

2023-05-08 17:59 UTC, ally-sassman commented on src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx
> +To upload your results automatically to a New Relic account when the Diagnostics CLI is executed, use either the `-attach` or `-api-key` command line flags. The `-attach` flag will validate any New R
```suggestion
To upload your results automatically to a New Relic account when the Diagnostics CLI is executed, use either the `-attach` or `-api-key` command line flags. The `-attach` flag will validate any New Relic license keys found in your environment and upload the run to the account associated with the license key. Alternatively, the `-api-key` flag will use the <InlinePopover type="userKey" /> provided to upload the run, regardless of the presence of a valid license key.
```

2023-05-08 17:59 UTC, ally-sassman commented on src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx
> +  - [Read more here](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag/#automatic-api)
```suggestion
  - [Read more here](/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag/#automatic-api)
```

2023-05-08 18:00 UTC, ally-sassman commented on src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx
> +### Python Agent
```suggestion
### Python agent
```

2023-05-08 18:00 UTC, ally-sassman commented on src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx
> +### New Feature
```suggestion
### New features
```

2023-05-08 18:01 UTC, ally-sassman commented on src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx
> +  - [Read more here](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag/#automatic-api)
```suggestion
`-api-key` command line flag
  * Use your <InlinePopover type="userKey" /> to automatically attach a Diagnostics CLI run to your account. This bypasses the requirement for a validated license key to attach a run.
  * Example usage: `./nrdiag -api-key NRAK-123...............`
  * [Read more here](/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag/#automatic-api)
```

2023-05-08 18:01 UTC, ally-sassman commented on src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx
> +### New Feature
```suggestion
### New feature
```

2023-05-08 18:01 UTC, ally-sassman commented on src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx
> +- **Python/Requirements/PythonVersion:** Update New Relic Agent Supportability for Python 3.6, 3.9, 3.10, and 3.11.
```suggestion
- **Python/Requirements/PythonVersion:** Update New Relic agent supportability for Python 3.6, 3.9, 3.10, and 3.11.
```

2023-05-08 18:02 UTC, ally-sassman commented on src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/interpret-nrdiag-output.mdx
>  2. Optional: Click the star next to the icon to add it to your favorites.
```suggestion
2. (Optional) Click the star next to the icon to add it to your favorites.
```

2023-05-08 18:02 UTC, ally-sassman requested changes
Reviewed with a few suggested changes.

2023-05-08 19:29 UTC, daffinito commented
@ally-sassman Thank you for the suggestions! I committed them!

2023-05-08 20:34 UTC, ally-sassman commented on src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx
> +releaseDate: '2023-05-04'
```suggestion
releaseDate: '2023-05-08'
```
Should this be changed to today's date?

2023-05-08 20:41 UTC, daffinito commented on src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx
> +releaseDate: '2023-05-04'
oh yeah probably, thank you!

2023-05-08 20:59 UTC, ally-sassman approved these changes

2023-05-08 21:01 UTC, merged