fix(docs): Adds security recommendations for Azure ARM templates to forward logs
newrelic/docs-website pull request #13091
Opened 2023-05-17 14:12 UTC by jsubirat

* What problems does this PR solve?
Adds a new section to explain how to strengthen the security of a log forwarding setup deployed using any of our Azure ARM templates.

* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
This documentation explains how to manually perform the steps to reconfigure an already existing log forwarding setup to use the enhancements that were introduces in [this PR](https://github.com/newrelic/newrelic-azure-functions/pull/79) and [this PR](https://github.com/newrelic/newrelic-azure-functions/pull/80).

2023-05-17 14:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=13091) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=13091) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: steve-cunnew<br/>:white_check_mark: zuluecho9<br/>:white_check_mark: clarkmcadoo<br/>:x: jsubirat<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=13091) it.</sub>

2023-05-17 14:14 UTC, jsubirat commented
Hi folks, this PR is still being worked on, I'll move the Draft flag once we're ready for a review from your side. Many thanks in advance!

2023-05-19 15:59 UTC, jsubirat commented
Hi docs team, the PR is now ready to be reviewed, thanks!

2023-05-22 21:31 UTC, rkbodenner requested changes
This looks ready to ship, with the one date typo to be fixed.

2023-05-22 21:31 UTC, rkbodenner commented on src/content/docs/logs/forward-logs/azure-log-forwarding.mdx
> +In May 2013, we included some security enhancements in our ARM templates that modify the settings in the Storage Account and the Function App deployed using those templates. Azure resources are secur
```suggestion
In May 2023, we included some security enhancements in our ARM templates that modify the settings in the Storage Account and the Function App deployed using those templates. Azure resources are secured by default and these changed settings prevent this secure default state from being modified.
```

2023-05-23 10:21 UTC, x8a approved these changes
Thanks a lot for your edits!

2023-05-23 13:10 UTC, merged