Added feature flags and release notes for 7.4.5 release
newrelic/docs-website pull request #13177
Opened 2023-05-23 15:46 UTC by mbruin-NR

I added the iOS agent 7.4.5 release notes and some information about new feature flags in the release

2023-05-23 15:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=13177) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=13177) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=13177) it.</sub>

2023-05-23 15:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=13177) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=13177) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=13177) it.</sub>

2023-05-23 16:55 UTC, cdillard-NewRelic requested changes
Looks good but don't forget to update the EOL page:

https://github.com/newrelic/docs-website/pull/12643/files
See changes to https://github.com/newrelic/docs-website/pull/12643/files#diff-765adbdb5c9cc4693e22931b1d502e526a7b132baa86ff2f34eed1b90d3088c5

2023-05-30 14:39 UTC, rhetoric101 approved these changes
@mbruin-NR these changes look good. We'll get these published on Wednesday, May 31st.

2023-05-31 15:03 UTC, merged