Update product-capability-feature-usage.mdx
newrelic/docs-website pull request #13213
Opened 2023-05-25 16:26 UTC by bhecknr

Added information about how to refer to New Relic Grok.

2023-05-25 16:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=13213) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=13213) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=13213) it.</sub>

2023-05-25 16:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=13213) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=13213) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=13213) it.</sub>

2023-05-25 17:10 UTC, ally-sassman submitted a review, later dismissed

2023-05-25 20:06 UTC, mmfred requested changes
See my change requests. Thanks.

2023-05-25 20:06 UTC, mmfred commented on src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
> +        Do not use: New Relic grok, Grok (unless preceded by "New Relic")
```suggestion
        Do not use: New Relic grok, Grok (unless preceded by "New Relic"), GROK 
        
        Note that there are other tools (not associated with New Relic) called "Grok." For these, always specify the company name to ensure readers understand that we're not referring to New Relic Grok.
```

2023-05-25 20:06 UTC, mmfred commented on src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
> +        Do not use: New Relic grok, Grok (unless preceded by "New Relic")
```suggestion
        Do not use: New Relic grok, Grok (unless preceded by "New Relic"), GROK 
        
        Note that there are other tools (not associated with New Relic) called "Grok." For these, always specify the company name to ensure readers understand that we're not referring to New Relic Grok.
```

2023-05-25 20:06 UTC, mmfred commented on src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
> +        - The product is New Relic Grok, and that's how we want to present it.
Please remove the bullet points below, from "If you're using grok by itself" through to the end of the content in this table cell. I added some of this info to the "do not use" column. And it's in the wrong spot. Also, just trying to keep this table consistent.

2023-05-25 23:09 UTC, ally-sassman commented on src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
>          - Don't use "GROK" (all uppercase) on its own to avoid the capitalization and sentence-starting rules described in the previous bullets.
```suggestion
```

2023-05-25 23:09 UTC, ally-sassman commented on src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
> +        - Don't use "GROK" (all uppercase) on its own to avoid the capitalization and sentence-starting rules described in the previous bullets.
```suggestion
```

2023-05-30 23:32 UTC, ally-sassman commented on src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
> +        - Subsequent uses: New Relic Grok
```suggestion
        The product is New Relic Grok, and that's how we want to present it.
        * First use: New Relic Grok
        
        * Subsequent uses: New Relic Grok
```

2023-05-30 23:34 UTC, ally-sassman approved these changes

2023-06-02 21:29 UTC, merged