fix:add lets encrypt to docs
newrelic/docs-website pull request #13876
Opened 2023-07-17 15:57 UTC by bindu90

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

2023-07-17 15:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=13876) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=13876) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=13876) it.</sub>

2023-07-17 17:10 UTC, nr-dbuckwalter requested changes
In my opinion, adding another Root CA to the documentation is going in the wrong direction, as this list is not complete.  We should instead remove instructions for importing specific root CAs.
There are [currently 15 different Root CAs that have issued valid, non-expired certificates](https://crt.sh/?identity=newrelic.com&exclude=expired&dir=^&sort=1&group=icaid) for [newrelic.com](http://newrelic.com/) domains.

2023-07-31 13:51 UTC, zuluecho9 commented
@bindu90 Did you see Damon's comment above? Curious what you think of that

2023-08-01 19:43 UTC, closed without merging

2023-08-01 19:43 UTC, bindu90 commented
will update in different PR