NR-118734 docs for entity signals component
newrelic/docs-website pull request #14050
Opened 2023-07-28 21:21 UTC by Marty42Martinez

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

This PR will add docs for the recently released Distributed tracing Entity Signals component that can be found on the APM Summary page.

2023-07-28 21:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=14050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=14050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=14050) it.</sub>

2023-08-02 19:06 UTC, Marty42Martinez commented
gatsby clean

2023-08-02 22:14 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +The Distributed trace insights component surfaces three types of performance signals from related traced entities.
```suggestion
The distributed trace insights component surfaces three types of performance signals from related traced entities.
```

2023-08-02 22:37 UTC, ally-sassman requested changes

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +## Summary of trace Insights
```suggestion
## Summary of trace insights
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +1. **Call path direction**: `Upstream | Downstream` followed by the average number of entities (hops) in the call path
```suggestion
1. **Call path direction**: `Upstream | Downstream` followed by the average number of entities (hops) in the call path.
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +    * Downstream: Insight data is generated from call paths which follow calls from your entity and include the listed entity.
```suggestion
    * `Upstream`: Insight data is generated from call paths from the listed entity to your entity.
    * `Downstream`: Insight data is generated from call paths that follow calls from your entity and include the listed entity.
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +2. Selected Signal insights:Each item displays its performance for the selected signal at the top, including a trend arrow (up or down; when data is available), signal value, & percent change of the
```suggestion
2. **Selected signal insights**: Each item displays its performance for the selected signal at the top, including a trend arrow (up or down when data is available), signal value, and percent change of the signal value (when data is available).
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +Percent change: The time window for this value is defined by a combination of the time picker & Compare with dropdown values. Percent change will not be shown when previous tracing data is unavailabl
```suggestion
3. **Percent change**: The time window for this value is defined by a combination of the time picker and comparison with dropdown values. Percent change will not be shown when previous tracing data is unavailable; this generally occurs when the time window extends past 3 days before the present time.
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +3. Entity health icon: This icon will change status color based on the `Alert Severity` that the listed entity reports.
```suggestion
4. **Entity health icon**: This icon will change status color based on the `Alert Severity` that the listed entity reports.
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +4. Entity: The name of the entity reporting insights that impact your entity for the selected signal.
```suggestion
5. **Entity**: The name of the entity reporting insights that impact your entity for the selected signal.
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +5. Non-selected Signals: Each item will also report the signal value and percent change (when available) for the 3 signals that are not actively selected. Those signals are defined as:
```suggestion
6. **Non-selected signals**: Each item will also report the signal value and percent change (when available) for the three signals that are not actively selected. Those signals are defined as:
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +7. View Trace button: Clicking on this button will open a pane to the [trace details UI](/docs/distributed-tracing/ui-data/trace-details/). You will view a trace that contains your entity, the listed
```suggestion
7. **Sparkline chart**: Includes 2 timeseries of the Selected Signal value, this chart has mouse hover interactions that sync with all timeseries charts on the page. The timeseries in color covers the time window defined by the time picker while the gray timeseries presents previous data (covering the same duration) that is used for comparison.
8. **View Trace button**: Clicking on this button will open a pane to the [trace details UI](/docs/distributed-tracing/ui-data/trace-details/). You will view a trace that contains your entity, the listed entity, and similar values for the Selected Signal. Additionally, the waterfall will render highlighted rows for spans connected to the listed entity.
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +Lists have an initial limit of 20 entities; in the event that there are more than 20 entities with a significant performance impact a `Show More` button appears at the bottom of the list.
```suggestion
Lists have an initial limit of 20 entities; in the event that there are more than 20 entities with a significant performance impact a **Show More** button appears at the bottom of the list.
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +* last week: Comparison time window will end 7 days before the beginning of the time picker window.
```suggestion
* **None**: The comparison time window will end at the beginning of the time picker window.
* **Yesterday**: The comparison time window will end one day before the beginning of the time picker window.
* **Last week**: The comparison time window will end 7 days before the beginning of the time picker window.
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +If there is no tracing data preserved in the comparison window, the Distributed trace insights subheader will not contain a "compared with" clause.
```suggestion
If there is no tracing data preserved in the comparison window, the distributed trace insights subheader will not contain a "compared with" clause.
```

2023-08-02 22:37 UTC, ally-sassman commented on src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
> +If your entity is not reporting trace data, the entity insights component will present a no data view that provides links to our docs and a Guided Install solution.
```suggestion
If your entity is not reporting trace data, the entity insights component will present a "no data" view which includes links to our docs and a Guided Install setup.
```

2023-08-02 22:38 UTC, ally-sassman approved these changes

2023-08-02 22:46 UTC, merged