chore: Pass className prop to MDX container
newrelic/docs-website pull request #14584
Opened 2023-09-13 21:05 UTC by tabathadelane

a future theme update will add these features:

- Add max height for MDX images at 550px
- Unsets this height in lightbox view
- An 'unbound' class for `<img>` in MDX files to unset this height restriction where authors deem it is appropriate.
  - `className="unbound"`
  - **this PR allow us to pass this className**

2023-09-18 17:55 UTC, sunnyzanchi requested changes

2023-09-18 17:55 UTC, sunnyzanchi commented on src/components/MDXContainer.js
> +        className={props.width ? 'unbound' : props.className}
hmm would it be better have `unbound` in addition to any className passed in?

```suggestion
        className={cx(props.className, props.width && 'unbound')}
```

2023-09-19 21:08 UTC, sunnyzanchi submitted a review, later dismissed

2023-12-01 23:35 UTC, austin-schaefer commented
@tabathadelane : Is this still a PR we're actively working? If not can we close and reopen the related Jira for the backlog?

2023-12-07 19:54 UTC, tabathadelane commented
> @tabathadelane : Is this still a PR we're actively working? If not can we close and reopen the related Jira for the backlog?

Yes, this ticket, NR-118948, is still open (blocked) in our On-Deck list. This works needs to merge in with a theme update, but the theme has been blocked by Gastby 5 upgrades. We are doing work this sprint to to unblock it for UX work. I will get visibility on it with the team.

2023-12-07 19:57 UTC, tabathadelane commented
reopening to trigger new checks that we have added since this was created.

2023-12-11 17:53 UTC, clarkmcadoo approved these changes

2023-12-11 20:03 UTC, sunnyzanchi submitted a review, later dismissed
tested again and looks good to me!

2023-12-12 16:40 UTC, tabathadelane commented
[successfully built after cache clear](https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/pull-requests/6297689c-c59a-48ea-b717-bf2dae18c8f1/builds?loggedin=1&token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2QxNzU3Ny0zZWVmLTQzMjMtODBlNC1kZmRiYjk0NDNkZmQiLCJlbWFpbCI6InRhYmF0aGFkZWxhbmVAZ21haWwuY29tIiwiaWF0IjoxNzAyMzk5MDc2LCJleHAiOjE3MDI0NDIyNzYsImlzcyI6IkdhdHNieSBJbmMiLCJzdWIiOiJ0YWJhdGhhZGVsYW5lQGdtYWlsLmNvbSJ9.Q1QKwOBGgJU3z4xcK4-HaDjYE6Cs8-JULfEy-9589j_pgh_34WlLIJSyInNbFW-vObCTNgVQYn8EQLc9wOlVQ8i6kMoQEJKb6jnSl3V9BuBf5O0VzWHHQ74PPytLqAxRVNfndrVtnVmhNJqZb3a2MPda5ysIMYz2e52RnyhXhmIGobq3Xvus4utier4M4tZZVOW5SGLCaYIWwV4ex45ckKgfMsiG3E6CX1okGW2n1mre74-q6CHZVpIwbNet0RC-zxxplJUHkwY-Tzwg9MsteyyYA2UjVEELhxK5bIhFBndywVVBk2gOSZEbwJ4zVLcOhRuOYLAYBiTE773hx37v82lGk56yHlv12L7zuEnXzSEVHYD4raskuplODhC6tDlHzcSMQUQOb00qQaZQclOPKXv8fyrSKPI3er3eoQ7PtZtdXQsbTkZZYNvDTrHOMGcLjqsRo684Bp6ozSWXagFSqtu9E4xR25rjNyZdOmOLoAcodSMDq4QFWOsl_gIRrIEYN5vX979BpyTix6EhopT_mshuiXPXeuynZyJ0M1ZSDWvYizwhY832_ofJr-HH57arFssMi3xREMwN8L-XVsjFDopGNHvJ3WLgbFvfRicSTwYcaZNUsog4w9Lhwhfbq0__Ze-EfTKcaqTDkeOHg2lIcVzAPyyfuo4YYvsZ7HfYWx0&expiration=2023-12-26T16%3A37%3A56.117Z&ssoToken=&ssoExpiration=&id=63d17577-3eef-4323-80e4-dfdbb9443dfd&loginRedirectUrl=%2Fdashboard%2F34e708d2-68a1-48ca-b66f-d2604890b061%2Fsites%2Fa0b77314-cdea-4790-8fde-7d3457d590ce%2Fpull-requests%2F6297689c-c59a-48ea-b717-bf2dae18c8f1%2Fbuilds&selectedPlan=&redirectToLeadCapture=false)

2023-12-12 16:57 UTC, clarkmcadoo approved these changes

2023-12-12 16:58 UTC, sunnyzanchi approved these changes

2023-12-12 17:01 UTC, merged