Android agent v7.1.0 release notes
newrelic/docs-website pull request #14624
Opened 2023-09-18 22:07 UTC by ywang-nr

Ticket: https://issues.newrelic.com/browse/NR-160141
* What problems does this PR solve? - Android agent release notes

2023-09-18 22:07 UTC, ywang-nr commented
@ndesai-newrelic for hybrid review

2023-09-19 15:59 UTC, cthomas-newrelic requested changes
Awesome.

2023-09-19 15:59 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-710.mdx
> +<Callout variant="important">
We can remove this now that 7.0.0 has shipped

2023-09-19 15:59 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-710.mdx
> +* Decouple map tagging with uploads in plugin to improve the build pipeline by making the tagged map a cachable build artifact
That is very good!

2023-09-19 15:59 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-710.mdx
> +* Fix NoClassDefFoundError when using agent v7.0.0 due to SHA signed libraries are not instrumented
How about, "
* Fix NoClassDefFoundError when using agent v7.0.0 due to uninstrumented signed libraries"?

2023-09-19 15:59 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-710.mdx
> +* Fix an issue that excludeVariantInstrumention is not taking camal case variants
"... not accepting camel case variant names"

2023-09-19 15:59 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-710.mdx
> +* Fix an issue with obfuscated attribute due to field name change
This is entirely internal and can be removed.

2023-09-25 19:19 UTC, homelessbirds approved these changes

2023-09-25 19:19 UTC, merged