fix(kafka): clarifying docs
newrelic/docs-website pull request #14821
Opened 2023-10-10 12:48 UTC by paologallinaharbur

## Give us some context

Considering a single broker and two topics scraped, we get two samples attached to the same entity:
```
      "entity": {
        "name": "kafka-0.kafka-headless.can-kafka.svc.cluster.local:9092",
        "type": "ka-broker",
[...]
      "metrics": [
        {
          "broker.bytesWrittenToTopicPerSecond": 0,
          "clusterName": "kafka-canary",
          "displayName": "kafka-0.kafka-headless.can-kafka.svc.cluster.local:9092",
          "entityName": "broker:kafka-0.kafka-headless.can-kafka.svc.cluster.local:9092",
          "event_type": "KafkaBrokerSample",
          "topic": "topicA",
          "topic.diskSize": 197053793,
          "topic.offset": 2403128
        },
        {
          "broker.bytesWrittenToTopicPerSecond": 0,
          "clusterName": "kafka-canary",
          "displayName": "kafka-0.kafka-headless.can-kafka.svc.cluster.local:9092",
          "entityName": "broker:kafka-0.kafka-headless.can-kafka.svc.cluster.local:9092",
          "event_type": "KafkaBrokerSample",
          "topic": "__consumer_offsets",
          "topic.diskSize": 23889855,
          "topic.offset": 4808573
        }
```

Moreover, topic.diskSize is not included in the KafkaTopicSample:
```
       {
          "clusterName": "kafka-canary",
          "displayName": "topicA",
          "entityName": "topic:topicA",
          "event_type": "KafkaTopicSample",
          "topic.partitionsWithNonPreferredLeader": 0,
          "topic.respondsToMetadataRequests": 1,
          "topic.underReplicatedPartitions": 0
        }
```

2023-10-10 16:43 UTC, ally-sassman commented on src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx
> +            Topic offset per broker and per topic. Only present if COLLECT_TOPIC_OFFSET is enabled.
```suggestion
            Topic offset per broker and per topic. Only present if `COLLECT_TOPIC_OFFSET` is enabled.
```

2023-10-10 16:46 UTC, ally-sassman requested changes
@paologallinaharbur See my suggestions. Let me know if they're good to merge.

2023-10-11 08:34 UTC, paologallinaharbur commented
Yes, they are! 😄

2023-10-11 17:21 UTC, ally-sassman approved these changes

2023-10-11 17:22 UTC, merged