fix: infra-agent settings in beanstalk docs
newrelic/docs-website pull request #15014
Opened 2023-10-30 11:24 UTC by josemore

## Give us some context

* Add a section to the infra agent Beanstalk installation instructions explaining how to configure the agent.

2023-10-30 22:11 UTC, ally-sassman commented on src/content/docs/infrastructure/new-relic-infrastructure/troubleshooting/network-connection-issues.mdx
> +1. **Resolve the domain:** Use nslookup or dig to validate that the Linux system can resolve the domain to an IP address:
```suggestion
1. **Resolve the domain:** Use `nslookup` or `dig` to validate that the Linux system can resolve the domain to an IP address:
```

2023-10-30 22:11 UTC, ally-sassman commented on src/content/docs/infrastructure/new-relic-infrastructure/troubleshooting/network-connection-issues.mdx
> +4. **Curl:** Use curl to check if the endpoint is reachable:
```suggestion
4. **Curl:** Use `curl` to check if the endpoint is reachable:
```

2023-10-30 22:13 UTC, ally-sassman commented on src/content/docs/infrastructure/new-relic-infrastructure/troubleshooting/network-connection-issues.mdx
> +[Code Implementation](https://github.com/newrelic/newrelic-diagnostics-cli/blob/main/tasks/infra/agent/connect.go#L48)
@josemore What's the purpose of this link? Can you add something before this link, like what readers would expect to see from this link or why they'd want to go to it?

2023-10-30 22:13 UTC, ally-sassman commented on src/content/docs/infrastructure/new-relic-infrastructure/troubleshooting/network-connection-issues.mdx
> +Note that the nrdiag Connect task result is shown in stdout, it should be collected with the `nrdiag_output.zip` file.
```suggestion
Note that the `nrdiag Connect` task result is shown in `stdout`, it should be collected with the `nrdiag_output.zip` file.
```

2023-10-30 22:14 UTC, ally-sassman requested changes
See my comments

2023-10-31 08:28 UTC, josemore commented
thanks @ally-sassman, I removed the "network troubleshooting" doc, I'll submit that one in a different PR and already adapted based on your feedback.

2023-10-31 16:26 UTC, ally-sassman approved these changes

2023-10-31 16:26 UTC, merged