docs freshness
newrelic/docs-website pull request #15270
Opened 2023-11-17 23:43 UTC by tabathadelane

### ✨ Summary

### 🔮 Engineering checklist

- [ ] Relevant documentation including README's or Confluence are updated to reflect these changes
- [ ] Code changes are self-documenting or clearly commented/documented
- [ ] Changes that effect tech writers have been communicated to tech docs team
- [ ] New components created for use in MDX files have been serialized/deserialized
- [ ] New tests are added where applicable and total coverage remains >70%
- [ ] No new warnings or errors where added to the browser or build console
- All downstream dependencies for DaaS have been considered for negative impacts
  - [ ] What's new JSON endpoints
  - [ ] Release notes JSON & EOL pages
- [ ] The build preview has been checked for expected functionality on desktop browsers
- [ ] The build preview has been checked for expected functionality on mobile browsers
- [ ] Synthetics tests have been considered for any changes that might trigger false positives

2023-11-22 17:45 UTC, sunnyzanchi requested changes
i appreciate the tests! i left a couple comments

2023-11-22 19:44 UTC, tabathadelane commented on scripts/addFreshnessFrontmatter.mjs
> +    const content = fileData.split('---');
Parsing was easy, but re-writing was causing a lot of inconsistencies with our frontmatter that use quotes(metaDescription mostly). I tried a handful of npm packages and nothing was working well.

2023-11-28 16:19 UTC, roadlittledawn commented
ran `node scripts/addFreshnessFrontmatter` locally. as it ran files showed as deleted in git history. but when i came back to it, looks like all files were modified, frontmatter added as expected, and none were deleted

2023-11-28 17:22 UTC, sunnyzanchi approved these changes

2023-11-28 20:19 UTC, merged