Update nerdgraph-entities-api-tutorial.mdx
newrelic/docs-website pull request #15607
Opened 2023-12-21 16:41 UTC by v-aparna

pass atlease message subfield , other wise the query fails

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
Fixes the graphql query to delete an entity
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

2023-12-21 16:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=15607) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=15607) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=15607) it.</sub>

2023-12-21 16:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=15607) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=15607) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=15607) it.</sub>

2023-12-21 20:40 UTC, ajtran303 commented on src/content/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial.mdx
> +    }
This mutation could be improved by providing the GUIDS of failed entity deletions and possibly the error types.

```graphql
    failures {
      guid
      message
      type
    }
```

2023-12-21 20:47 UTC, ajtran303 requested changes
My suggestion is to also return guids when getting info about failed deletions.  

`guid` is necessary because if one or several deletions fail in a collection of entities, this guide does not currently have information for a user to identify which entities did not delete.

2023-12-21 21:43 UTC, ajtran303 commented
Additionally, this document should be updated to include information about using the `AgentApplication` delete mutation for APM applications. APM entity deletions are not supported by this current mutation, as I understand it.

2023-12-21 21:46 UTC, ajtran303 commented
Other entities, such as Browser and Mobile can also be deleted with the mutation mentioned above.

2024-01-05 21:37 UTC, jeff-colucci approved these changes

2024-01-05 22:07 UTC, merged