docs: Python Agent v9.5.0 Release
newrelic/docs-website pull request #15807
Opened 2024-01-12 00:47 UTC by TimPansino

## Give us some context

* Add release notes for Python agent v9.5.0
* Update settings and API documentation for changes in this version

2024-01-12 00:52 UTC, TimPansino commented
Would be very helpful to get this out ASAP since we did a release at the end of our day. If you have any suggestions feel free to commit them and merge this, and I can open a follow up PR later if I have anything to address.

2024-01-12 23:47 UTC, ally-sassman commented on src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
> +    If attributes are enabled for context_data, all attribute keys found in this list will be sent to us in transaction traces. For more information, see the [agent attribute rules](/docs/apm/other-f
```suggestion
    If attributes are enabled for `context_data`, all attribute keys found in this list will be sent to us in transaction traces. For more information, see the [agent attribute rules](/docs/apm/other-features/attributes/agent-attributes).
```

2024-01-12 23:47 UTC, ally-sassman commented on src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
> +      When adding context attributes, the agent prefixes the keys with `context.` for attributes from the logging framework context, and `message.` for attributes from a dictionary message context.
Just confirming the `.` is not a typo in `context` and `message`?

2024-01-12 23:48 UTC, ally-sassman commented on src/content/docs/apm/agents/python-agent/python-agent-api/recordlogevent-python-agent-api.mdx
> +An example of recording a log event using message attributes and context attributes
```suggestion
Here's an example of recording a log event using message attributes and context attributes:
```

2024-01-12 23:49 UTC, ally-sassman commented on src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90500.mdx
> +This release of the Python agent adds context data attributes to logs, support for dictionary type log messages, adds attribute support to `record_log_event` API, and obfuscation of logged license ke
```suggestion
This release of the Python agent adds context data attributes to logs, support for dictionary type log messages, adds attribute support to `record_log_event` API, and obfuscates logged license keys and user API keys.
```

2024-01-12 23:50 UTC, ally-sassman commented on src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90500.mdx
> +To report these attributes, [enable context data forwarding](/docs/agents/python-agent/configuration/python-agent-configuration#application_logging.forwarding.context_data.enabled) and optionally con
```suggestion
* **Add context data attributes to logs**
    * Context data available from logging frameworks can now be recorded as attributes on logs. These attributes are prefixed with `context.`, which is not considered when filtering attributes from logs.
    * Context data may include extras, dictionary message attributes, and attributes provided by logging frameworks.
    * To report these attributes, [enable context data forwarding](/docs/agents/python-agent/configuration/python-agent-configuration#application_logging.forwarding.context_data.enabled) and optionally configure [include](/docs/agents/python-agent/configuration/python-agent-configuration#application_logging.forwarding.context_data.include) and [exclude](/docs/agents/python-agent/configuration/python-agent-configuration#application_logging.forwarding.context_data.exclude) rules to filter the allowed attributes.
```

2024-01-12 23:51 UTC, ally-sassman commented on src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90500.mdx
> +The agent now obfuscates all instances of license keys or user API keys in agent logs and audit logs.
```suggestion
* **Add support for dictionary type log messages**

    * Dictionary type log messages are now supported for logging frameworks which support dictionary type log messages (including the builtin `logging` module and `structlog`). 
    * The key `message` will be extracted if available and treated as the log message, and any other items will be considered context data attributes and prefixed with `message.`. These attributes are subject to the same filtering rules as other context data.

* **Add attribute support to `record_log_event` API**

    * The `record_log_event` API now allows passing context data in using the optional `attributes` keyword argument, and allows the message argument to be a dictionary as described above.

* **Obfuscate license keys and user API keys in logs**

    * The agent now obfuscates all instances of license keys or user API keys in agent logs and audit logs.
```

2024-01-12 23:52 UTC, ally-sassman requested changes
See my suggestions.

2024-01-13 00:29 UTC, ally-sassman approved these changes

2024-01-13 01:06 UTC, merged