Update opentelemetry docs to prefer OTLP http/protobuf over grpc
newrelic/docs-website pull request #15846
Opened 2024-01-17 18:30 UTC by jack-berg

The grpc version of OTLP causes problems compared to http/protobuf. This PR updates all the OpenTelemetry docs to prefer http/protobuf. 

The OpenTelemetry docs reference examples in [newrelic/newrelic-opentelemetry-examples](https://github.com/newrelic/newrelic-opentelemetry-examples). The following PRs update all the examples in that repo to prefer http/protobuf over grpc as well:

- https://github.com/newrelic/newrelic-opentelemetry-examples/pull/524
- https://github.com/newrelic/newrelic-opentelemetry-examples/pull/523
- https://github.com/newrelic/newrelic-opentelemetry-examples/pull/522
- https://github.com/newrelic/newrelic-opentelemetry-examples/pull/521
- https://github.com/newrelic/newrelic-opentelemetry-examples/pull/520
- https://github.com/newrelic/newrelic-opentelemetry-examples/pull/519

2024-01-17 18:44 UTC, jack-berg commented on src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-go.mdx
This file was odd. It doesn't appear in the navigation, but is linked to by [the metrics best practices page](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics/).

The problem is that the page is wrong. It seems to be a copy / paste of the [python getting started guide](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-python/), but was never updated to actually be a go getting started guide like the title states. 

Better to delete the document for now and re-add it when someone wants to properly add a go getting started page.

cc @reese-lee who committed the page

2024-01-18 17:53 UTC, kaylareopelle requested changes

2024-01-18 17:53 UTC, kaylareopelle commented on src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-java.mdx
> +            `OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.eu01.nr-data.net:` (For the EU)
```suggestion
            `OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.nr-data.net` (For the US)
            `OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.eu01.nr-data.net` (For the EU)
```

2024-01-18 17:53 UTC, kaylareopelle commented on src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-java.mdx
> +      * `OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.nr-data.net:`
```suggestion
      * `OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.nr-data.net`
```

2024-01-19 00:10 UTC, rhetoric101 approved these changes
@jack-berg thanks for tackling this sweeping update! This looks good!

2024-01-19 16:45 UTC, jeff-colucci approved these changes
All green, looks good to me!

2024-01-19 16:49 UTC, jack-berg commented
@jeff-colucci is there automated tooling for resolving the merge conflicts or should I take care of that?

2024-01-19 16:52 UTC, jeff-colucci commented
@jack-berg Unfortunately, there is no automated tool that I'm aware of for branch conflicts, so they have to be resolved manually. I'm not sure where these branch conflicts came from since they weren't there when I approved the request I don't think.

2024-01-19 16:53 UTC, kaylareopelle commented on src/i18n/content/jp/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-android-gradle-android-studio.mdx
@jack-berg Are these android gradle/studio files related to OpenTelemetry? Why are they being deleted?

2024-01-19 16:56 UTC, jack-berg commented on src/i18n/content/jp/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-android-gradle-android-studio.mdx
I don't know. I didn't commit those changes [see commit [here](https://github.com/newrelic/docs-website/pull/15846/commits/50770de500e5238830066e234c6951701a9ba629)]. I assumed it was some sort of unrelated automated cleanup required to get the develop branch back healthy which was just being bundled with this PR by coincidence, but @rhetoric101 and @jeff-colucci may know more.

2024-01-19 16:57 UTC, kaylareopelle commented on src/i18n/content/jp/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-android-gradle-android-studio.mdx
The file I commented on went away, but there are still a few others.

2024-01-19 18:12 UTC, jeff-colucci commented on src/i18n/content/jp/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-android-gradle-android-studio.mdx
Hi guys! Thanks for fixing this. I was able to track down that there was a script that was run that deleted some orphaned translated files, and that seems to be where the discrepancy came from. I'm going to re-check the files now to make sure there are no more issues. We have an auto-translator that does our translation work for us, so if a translated doc that doesn't cause branch commits gets deleted, that translator will re-translate the files so we won't actually lose anything.

Apologies for the confusion and thanks for patiently sticking with us while we get this ticket worked on. Assuming there are no more branch conflicts I will go ahead and get this merged and we can mark it as done!

2024-01-19 18:14 UTC, jeff-colucci approved these changes
Everything checks out!

2024-01-19 18:14 UTC, merged