feat(NRQL): changed the file structure and new page titles
newrelic/docs-website pull request #15943
Opened 2024-01-24 21:48 UTC by jeff-colucci

Revamping the left nav for NRQL. Tasks:

- Change location of files in left nav
- Rename all NRQL help files for more clarity and consistency
- Add redirects
- Change existing links in docs to new links
- Create new TOC

2024-01-26 17:51 UTC, austin-schaefer commented
Moving PR review to @akristen so @jeff-colucci has feedback in time next week

2024-01-29 18:16 UTC, akristen commented on src/content/docs/nrql/nrql-examples/browserspa-nrql-query-examples.mdx
> +  - /docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/browserspa-nrql-query-examples
I don't think this is in the yml file. when I click it in the nav, it disappears

2024-01-29 18:18 UTC, akristen commented on src/nav/nrql.yml
> +        path: /docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/browserspa-nrql-query-examples
```suggestion
        path: /docs/nrql/nrql-examples/browserspa-nrql-query-examples/
```

2024-01-29 18:21 UTC, akristen commented on src/nav/nrql.yml
> +        path: /docs/telemetry-data-platform/get-data/apis/query-metric-data-type
It is a bit jarring to be sent out of the NRQL category -- it definitely confused me when it first happened. Not sure if there's a solution tho

2024-01-29 18:21 UTC, akristen commented on src/nav/nrql.yml
> +        path: /docs/telemetry-data-platform/get-data/apis/query-metric-data-type
```suggestion
        path: /docs/telemetry-data-platform/get-data/apis/query-metric-data-type
```

re: the comments, this link

2024-01-29 18:22 UTC, akristen requested changes
There is one thing in the YML file that needs to be updated. Once that gets fixed, I'll approve! There's one other doc that i had a Q about, but if that link is intentional then don't worry about it.

2024-01-29 19:23 UTC, jeff-colucci commented on src/nav/nrql.yml
> +        path: /docs/telemetry-data-platform/get-data/apis/query-metric-data-type
Yeah, these are pre-existing dummy docs and we decided to keep them as they were for now, it's not ideal but it mirrors existing behavior

2024-01-29 20:38 UTC, akristen commented on src/nav/nrql.yml
> +        path: /docs/telemetry-data-platform/get-data/apis/query-metric-data-type
OK! That makes sense. I think it's fine :)

2024-01-29 20:41 UTC, akristen approved these changes
That link works! I'm approving. LMK if you ever revisit this work. I think it could be fun as a squad to think through the "Explore NRQL" category. IMO this is great and already a big improvement -- i could not tell you where our nrql docs were prior to this

2024-01-29 21:00 UTC, merged