feat(OHI IBM MQ): Added branching doc structure
newrelic/docs-website pull request #15981
Opened 2024-01-29 12:22 UTC by nbaenam

Added the branching doc structure for this page: [IBM MQ monitoring integration](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration).

This is the ticket: NR-217451

2024-01-31 07:33 UTC, bradleycamacho requested changes
Looks really good for the most part! I had a few larger structural changes I left comments about. Feel free to start revision before our call, or just wait for our call so I can explain further!

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/ibm-mq/intro.mdx
> +You can view this [metric data](#metrics) in pre-built <InlinePopover type="dashboards" />, create <InlinePopover type="alerts" /> policies, and create custom queries and charts.
I'd remove these popovers. They're nice in a way to introduce users to these NR concepts, but we want as few links out of the doc as possible (so users don't get lost)

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/ibm-mq/intro.mdx
> +To get data from IBM MQ infrastructure, our IBM MQ integration uses a third-party [Prometheus exporter](https://github.com/ibm-messaging/mq-metric-samples/tree/master/cmd/mq_prometheus), which expose
Not 100% sure, but "transforms them into entities" doesn't seem right. The specific infra being monitored by this integration install would be the entity.

I'd just cut out the "transforms them into entities"

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/ibm-mq/intro.mdx
> +Okay, let's get started installing your IBM MQ integration.
```suggestion
To start set up the IBM MQ integration, follow these steps:
```

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/config/ibm-mq.yaml
> +  - filePath: 'src/install/ibm-mq/default-install.mdx'
This doc is missing the step where the users pull down/download the actual integration. More info in comments below

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/ibm-mq/linux/install-linux.mdx
> +1. Change directory to the integrations configuration folder by running:
These looks good! The big issue here though, is these instructions refer to files that the user would not have at this point. The user needs to actually download the integration files reffered here. A bit hard to explain, but basically the users needs to "download" the integration by running a command. Once the command is run, the files used below appear.

See this step in the MongoDB doc: https://docs.newrelic.com/install/mongodb/#download-using-apt-4

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/config/ibm-mq.yaml
> +  - filePath: 'src/install/ibm-mq/configure.mdx'
I'd pull the configure examples and metric refrence out of the actual steps. These are reference material, and explicitly a seperate concept from the procedural content provided in the steps. 

See here: https://docs.newrelic.com/install/mongodb/#instance-settings

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/ibm-mq/linux/requirements-linux.mdx
> +* [Install the infrastructure agent](/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent-new-relic), minimum version 1.24.0.
I'd pull this out into it's own step: https://docs.newrelic.com/install/mongodb/#install-the-infrastructure-agent-3

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/ibm-mq/linux/requirements-linux.mdx
> +* Linux distribution compatible with the [infrastructure agent](/docs/infrastructure/new-relic-infrastructure/getting-started/compatibility-requirements-new-relic-infrastructure#operating-systems).
```suggestion

```

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/ibm-mq/linux/requirements-linux.mdx
> +* Linux distribution compatible with the [infrastructure agent](/docs/infrastructure/new-relic-infrastructure/getting-started/compatibility-requirements-new-relic-infrastructure#operating-systems).
They can find this info when installing the infra agent

2024-01-31 07:33 UTC, bradleycamacho commented on src/install/ibm-mq/linux/requirements-linux.mdx
> +* Check or add the libraries path in the `LD_LIBRARY_PATH` environment variable in Linux.
Should this be it's own step?

2024-02-12 02:41 UTC, bradleycamacho requested changes
There's something weird going on with this entire PR. Looks like there are a few hundred files changed somehow!

I think you somehow pulled an old version of the repo onto your branch, and GH thought those "old files" were files you updated.

Basically, this PR is reverting most of the site to an old release. I'd try to delete those changes, or just close this PR and open a new one with just the IBM MQ work.

2024-02-12 15:53 UTC, nbaenam commented
Hey @bradleycamacho, you're right. I'm going to close this PR and open a new one.

2024-02-12 15:53 UTC, closed without merging