[NR-260056] Android agent v7.3.1 release notes
newrelic/docs-website pull request #17053
Opened 2024-04-23 18:30 UTC by ywang-nr

* What problems does this PR solve? - Android agent v7.3.1 release notes

2024-04-23 18:33 UTC, ywang-nr commented
@cthomas-newrelic for review

2024-04-23 23:28 UTC, cthomas-newrelic requested changes

2024-04-23 23:28 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-731.mdx
> +* Resolve a SHA-signed error during build time by disabling JAR signing verification allows the agent plugin to read the classes without issues.
I'd remove `allows the agent plugin to read the classes without issues`.

2024-04-23 23:28 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-731.mdx
> +* Resolve reported ANRs during event persistance process.
Rather than _process_, how about `serialization`?

2024-04-25 19:40 UTC, rhetoric101 approved these changes
@ywang-nr thanks for adding these release notes!

2024-04-25 19:41 UTC, rhetoric101 commented
I have to do an administrative override because the Netlify checks didn't complete. I looked at the preview in Netlify.

2024-04-25 19:41 UTC, merged