feat(Dotnet): Consolodating APIs
newrelic/docs-website pull request #17266
Opened 2024-05-10 20:40 UTC by jeff-colucci

2024-05-22 21:04 UTC, jeff-colucci commented
Preview built and available at: https://deploy-preview-17266--docs-website-netlify.netlify.app/docs/apm/agents/net-agent/net-agent-api/net-agent-api/

2024-05-22 22:31 UTC, austin-schaefer requested changes
Hey Jeff, just finished a review. I found three types of things to address:

* Various rendering / structural things (visible anchor ID, missing collapser tags, tables-in-tables) that should be fixed before merge
* We need to account for existing links to these pages. Some of those are links w/in the page, but we should also account for existing links to individual methods in other docs that will break. We can create a separate Jira for that sweep but let's ensure we don't let it fall thru the cracks.
* Non-fatals: I found a lot of style/grammar/formattng errors and inconsistencies. I suspect many of those were pre-existing in the source docs, and I don't think we need to get these to 100%. But I'd like to fix the low-hanging fruit while we're working on this

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +metaDescription: 'A goal-focused guide to the New Relic .NET agent API.'
This meta-description feels outdated for the current scope of the doc.

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +freshnessValidatedDate: never
This should be updated

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +* Customizing your app name
Unnecessary -ing verbs

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +New Relic's .NET agent includes an API that allows you to extend the agent's standard functionality. For example, you can use the .NET agent API for:
```suggestion
New Relic's .NET agent includes an API that allows you to extend the agent's standard functionality. For example, you can use the .NET agent API to:
```

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    OR
I think this needs an extra line break or something to show up on its own line, in preview it shows up on same line

![Uploading image.png…]()

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Compare [`GetBrowserTimingHeader()`](/docs/agents/net-agent/net-agent-api/getbrowsertimingheader-net-agent), which <DoNotTranslate>**adds**</DoNotTranslate> the browser script to the page.
This was formerly a link to another doc, but now should presumably be an anchor link within the same doc. Would be good to check for other examples where links like this need updating.

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Compare [`GetBrowserTimingHeader()`](/docs/agents/net-agent/net-agent-api/getbrowsertimingheader-net-agent), which <DoNotTranslate>**adds**</DoNotTranslate> the browser script to the page.
I don't think `**adds**` should have the DNT tag

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    #### Disable automatic injection [#automatic-only]
These IDs dont work in the preview build, I think b/c h4s arent really supported/preferred 
<img width="437" alt="image" src="https://github.com/newrelic/docs-website/assets/55203603/204d7cc3-d16d-4079-adfa-0de5eef76fdd">

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Compare [`DisableBrowserMonitoring()`](/docs/agents/net-agent/net-agent-api/disablebrowsermonitoring-net-agent), which <DoNotTranslate>**disables**</DoNotTranslate> the browser script on a page.
Same link issue

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Returns an HTML snippet used to enable [<InlinePopover type="browser" />](/docs/browser/new-relic-browser/getting-started/new-relic-browser). The snippet instructs the browser to fetch a small Ja
```suggestion
    Returns an HTML snippet used to enable <InlinePopover type="browser" />. The snippet instructs the browser to fetch a small JavaScript file and start the page timer. You can then insert the returned snippet into the header of your HTML webpages. For more information, see [Adding apps to browser monitoring](/docs/browser/new-relic-browser/installation-configuration/adding-apps-new-relic-browser).
```

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Returns an HTML snippet used to enable [<InlinePopover type="browser" />](/docs/browser/new-relic-browser/getting-started/new-relic-browser). The snippet instructs the browser to fetch a small Ja
Two small errors here

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +            The per-request, cryptographic nonce used by Content-Security-Policy policies.
```suggestion
            The per-request, cryptographic nonce used by Content Security Policy policies.
```

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    #### With ASPX [#aspx]
Same h4 header ID issue

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    The Dictionary of key/value pairs returned includes items used to link traces and entities in the APM product. It will only contain items with meaningful values. For instance, if distributed trac
Why is `Dictionary` capped?

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +        `ITransaction.AcceptDistributedTraceHeaders` is used to instrument the called service for inclusion in a distributed trace. It links the spans in a trace by accepting a payload generated by [
For other methods, the syntax appears first and then description. Here description precedes syntax, and there's no short summaruy, only the long description

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +            Associates a User Id to the current transaction.
Why is `User Id` capped liek this?

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +        `ITransaction.InsertDistributedTraceHeaders` is used to implement distributed tracing. It modifies the carrier object that is passed in by adding W3C Trace Context headers and New Relic Distr
Same description issue as other DT method

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +        `ITransaction.InsertDistributedTraceHeaders` is used to implement distributed tracing. It modifies the carrier object that is passed in by adding W3C Trace Context headers and New Relic Distr
```suggestion
        `ITransaction.InsertDistributedTraceHeaders` is used to implement distributed tracing. It modifies the carrier object that is passed in by adding W3C Trace Context headers and New Relic Distributed Trace headers. The New Relic headers can be disabled with `<distributedTracing excludeNewrelicHeader="true" />` in the config. This method replaces the deprecated [`CreateDistributedTracePayload`](/docs/agents/net-agent/net-agent-api/itransaction#createdistributedtracepayload) method, which only creates New Relic distributed tracing payloads.
```

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +                Required. Container where Trace Context headers are inserted..
```suggestion
                Required. Container where trace context headers are inserted.
```

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +                Required. Caller-defined Action to insert header data into the carrier.
```suggestion
                Required. Caller-defined action to insert header data into the carrier.
```

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +            <table>
This table-in-a-table looks pretty nightmarish in builds, we should find another way to format it
<img width="686" alt="image" src="https://github.com/newrelic/docs-website/assets/55203603/738542eb-67d1-4537-b770-111db290c8b9">

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    For details about supported data types, see the [Custom Attributes Guide](/docs/agents/net-agent/attributes/custom-attributes).
```suggestion
    For details about supported data types, see [Custom attributes](/docs/agents/net-agent/attributes/custom-attributes).
```

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Associates a User Id with the current transaction.
why is `User Id` capped like this?

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    ### AddCustomAttribute [#addcustomattribute]
This seems to be missing a collapser to make it its own entry
![Uploading image.png…]()

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +            <table>
Same table-in-a-table issue as the other attribute method

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    ### SetName [#setname]
Missing collapser tags

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    ### Requirements [#requirements]
ID is bleeding thru in rendered doc
![Uploading image.png…]()

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    ### NoticeError(Exception) [#exception-overload]
should this be its own collapser?

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    ### NoticeError(Exception, IDictionary) [#exception-idictionary-overload]
should this be its own collapser?

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    ### NoticeError(String, IDictionary) [#string-idictionary-overload]
should this be its own collapser?

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    ### NoticeError(String, IDictionary, bool) [#string-idictionary-bool-overload]
should this be its own collapser?

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    * Custom Events are limited to 64-attributes.
```suggestion
    * Custom events are limited to 64 attributes.
```

Caps and hyphen here are weird

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    * Agent version 5.0.136.0 or higher.
5.0.136.0 is EOL ( https://deploy-preview-17266--docs-website-netlify.netlify.app/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy/ ), shouldn't this be all agent versions?

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    * Agent versions >= 10.9.0
Other calls say "or higher" rather than use puncutation

2024-05-22 22:31 UTC, austin-schaefer commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    * Agent version 5.0.136.0 or higher.
Same version comment as previous, this is EOl version

2024-06-03 18:50 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +            public interfac IAgent
Typo? 
```suggestion
            public interface IAgent
```
```suggestion
            public interfac IAgent
```

2024-06-03 18:50 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    public interfac ITransaction
Typo? 

```suggestion
    public interface ITransaction
```
```suggestion
    public interfac ITransaction
```

2024-06-03 18:50 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Public interfac ISpan
Typo? 

```suggestion
    Public interfac ISpan
```

2024-06-03 19:26 UTC, ally-sassman requested changes

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +        `ITransaction.AcceptDistributedTraceHeaders` is used to links the spans in a trace by accepting a payload generated by [`InsertDistributedTraceHeaders`](/docs/apm/agents/net-agent/net-agent-a
```suggestion
        `ITransaction.AcceptDistributedTraceHeaders` is used to links the spans in a trace by accepting a payload generated by [`InsertDistributedTraceHeaders`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#InsertDistributedTraceHeaders) or generated by some other W3C Trace Context compliant tracer. This method accepts the headers of an incoming request, looks for W3C Trace Context headers, and if not found, falls back to New Relic distributed trace headers. This method replaces the deprecated [`AcceptDistributedTracePayload`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#AcceptDistributedTracePayload) method, which only handles New Relic distributed trace payloads.
```
Maybe add a sentence about the new/recommended one after this

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +            [`AddCustomAttribute`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#add-custom-attr)
```suggestion
            [`AddCustomAttribute`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#AddCustomAttribute)
```

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    The agent adds the attributes only to the traced error; it does not send them to New Relic. For more information, see [`AddCustomAttribute()`](/docs/apm/agents/net-agent/net-agent-api/net-agent-a
```suggestion
    The agent adds the attributes only to the traced error; it does not send them to New Relic. For more information, see [`AddCustomAttribute()`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#AddCustomAttribute).
```

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Unique values like URLs, page titles, hex values, session IDs, and uniquely identifiable values should not be used in naming your transactions. Instead, add that data to the transaction as a cust
```suggestion
    Unique values like URLs, page titles, hex values, session IDs, and uniquely identifiable values should not be used in naming your transactions. Instead, add that data to the transaction as a custom parameter with the [`AddCustomAttribute()`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#AddCustomAttribute) call.
```
```suggestion
    Unique values like URLs, page titles, hex values, session IDs, and uniquely identifiable values should not be used in naming your transactions. Instead, add that data to the transaction as a custom parameter with the [`AddCustomAttribute()`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#add-custom-attr) call.
```

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Create user-related custom attributes. [`AddCustomAttribute`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#add-custom-attr) is more flexible.
```suggestion
    Create user-related custom attributes. [`AddCustomAttribute`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#AddCustomAttribute) is more flexible.
```

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    This call only allows you to assign values to pre-existing keys. For a more flexible method to create key/value pairs, use [`AddCustomAttribute()`](/docs/apm/agents/net-agent/net-agent-api/net-ag
```suggestion
    This call only allows you to assign values to pre-existing keys. For a more flexible method to create key/value pairs, use [`AddCustomAttribute()`](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#AddCustomAttribute).
```

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Define user-related [custom attributes](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#add-custom-attr)to associate with a browser page view (user name, account name, and product name).
```suggestion
    Define user-related [custom attributes](/docs/apm/agents/net-agent/net-agent-api/net-agent-api/#AddCustomAttribute)to associate with a browser page view (user name, account name, and product name). The values are automatically associated with pre-existing keys (`user`, `account`, and `product`), then attached to the parent APM transaction. You can also [attach (or "forward") these attributes](/docs/insights/new-relic-insights/decorating-events/insights-custom-attributes#forwarding-attributes) to browser [PageView](/docs/agents/manage-apm-agents/agent-metrics/agent-attributes#destinations) events.
```

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +        id="add-custom-attr"
```suggestion
        id="AddCustomAttribute"
```

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    If this method is invoked within a [transaction](/docs/glossary/glossary/#transaction), the agent reports the exception within the parent transaction. If it is invoked outside of a transaction, t
There's nothing on the errors inbox page about error trace

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +                Required. Specify a string to report to New Relic as though it's an exception. This method creates both [error events and error traces](/docs/tutorial-error-tracking/respond-outages/)
There's nothing about error events/error traces on that doc

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    This method only works when used within a transaction created using the `Transaction` attribute with the `Web` property set to `true`. (See [Instrument using attributes](/docs/agents/net-agent/ap
```suggestion
    This method only works when used within a transaction created using the `Transaction` attribute with the `Web` property set to `true` (see [Custom instrumentation via attributes](/docs/agents/net-agent/api-guides/net-agent-api-instrument-using-attributes)). It provides support for custom web-based frameworks that the agent does not automatically support.
```

2024-06-03 19:26 UTC, ally-sassman commented on src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
> +    Sets the URI of the current transaction. The URI appears in the 'request.uri' [attribute](/docs/agents/net-agent/attributes/net-agent-attributes) of [transaction traces](/docs/apm/transactions/tr
```suggestion
    Sets the URI of the current transaction. The URI appears in the `request.uri` attribute of [transaction traces](/docs/apm/transactions/transaction-traces/transaction-traces) and [transaction events](/docs/using-new-relic/metrics/analyze-your-metrics/data-collection-metric-timeslice-event-data), and it also can affect transaction naming.
```

2024-06-04 19:48 UTC, ally-sassman approved these changes

2024-06-04 19:48 UTC, merged