feat(Docs): Final steps in the dev-->docs site migration
newrelic/docs-website pull request #17627
Opened 2024-06-12 20:56 UTC by paperclypse

2024-06-13 22:34 UTC, homelessbirds commented on src/content/docs/new-relic-solutions/build-nr-ui/sdk-component/charts/Charts.mdx
This one looks weird- the url is `sdk-component/charts/Charts` is it meant to be double charts? Also, it's not in the nav

2024-06-13 22:34 UTC, homelessbirds requested changes
I just found one change!

2024-06-13 22:51 UTC, paperclypse commented on src/content/docs/new-relic-solutions/build-nr-ui/sdk-component/charts/Charts.mdx
It's one of the SDK component docs. They migrated in with these capitalized file names.  Thanks for catching it!

2024-06-14 15:52 UTC, homelessbirds approved these changes

2024-06-14 15:55 UTC, merged