Release go 3.34.0
newrelic/docs-website pull request #18219
Opened 2024-07-31 19:01 UTC by iamemilio

Prepares the Go agent docs for the 3.34.0 release

2024-07-31 19:25 UTC, ally-sassman commented on src/content/docs/logs/logs-context/configure-logs-context-go.mdx
> +## Supported Logging Libraries
```suggestion
## Supported logging libraries [#supported-libraries]
```

2024-07-31 19:26 UTC, ally-sassman commented on src/content/docs/logs/logs-context/configure-logs-context-go.mdx
> +        Supports Attribute Collection
```suggestion
        Supported attribute collection
```

2024-07-31 19:26 UTC, ally-sassman commented on src/content/docs/logs/logs-context/configure-logs-context-go.mdx
> +        [log](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/logWriter)
```suggestion
        [`logWriter`](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/logWriter)
```

2024-07-31 19:27 UTC, ally-sassman commented on src/content/docs/logs/logs-context/configure-logs-context-go.mdx
> +        [slog](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/nrslog)
```suggestion
        [`slog`](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/nrslog)
```

2024-07-31 19:27 UTC, ally-sassman commented on src/content/docs/logs/logs-context/configure-logs-context-go.mdx
> +        [Logrus](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/nrlogrus)
```suggestion
        [`nrlogrus`](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/nrlogrus)
```

2024-07-31 19:27 UTC, ally-sassman commented on src/content/docs/logs/logs-context/configure-logs-context-go.mdx
> +        [Zap](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/nrzap)
```suggestion
        [nrzap](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/nrzap)
```

2024-07-31 19:28 UTC, ally-sassman commented on src/content/docs/logs/logs-context/configure-logs-context-go.mdx
> +        [ZeroLog](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/zerologWriter)
```suggestion
        [`zerolog-writer`](https://github.com/newrelic/go-agent/tree/master/v3/integrations/logcontext-v2/zerologWriter)
```

2024-07-31 19:29 UTC, ally-sassman commented on src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-34-0.mdx
> +  - support for `RegisterTLSConfig` in nrmysql
```suggestion
  - `logcontext-v2/nrlogrus` can now collect user attributes
  - `logcontext-v2/nrslog` can now collect user attributes
  - Use `slog` to manage Go agent logs with the new `nrslog` library
  - Use `zerolog` go manage Go agent logs with the new `nrzerolog` library
  - Support for `RegisterTLSConfig` in `nrmysql`
```

2024-07-31 19:29 UTC, ally-sassman commented on src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-34-0.mdx
> +  - switched protobuff to google.golang.org/protobuff in modfile
```suggestion
  - `logcontext-v2/nrlogrus` will still print user logs without issues if the Go agent has already been shut down
  - Switched `protobuff` to `google.golang.org/protobuff` in `modfile`
```

2024-07-31 19:31 UTC, ally-sassman commented
@iamemilio Please see my suggestions. Let's keep the naming conventions the same for all the libraries (i.e., list them all by their code name).

2024-07-31 19:37 UTC, ally-sassman requested changes
See my comments/suggestions

2024-08-01 15:43 UTC, iamemilio commented
Hi @ally-sassman we are planning to defer the release to monday august 5th, just so you know.

2024-08-01 20:45 UTC, iamemilio commented
> See my comments/suggestions

Addressed! How does it look?

2024-08-01 21:49 UTC, ally-sassman approved these changes

2024-08-05 15:41 UTC, merged