fix(Dashboards): Updated screenshots
newrelic/docs-website pull request #18584
Opened 2024-09-06 11:19 UTC by nbaenam

Added an update on the [Chart refresh rates](https://docs.newrelic.com/docs/query-your-data/explore-query-data/use-charts/chart-refresh-rates/) page.

Ticket: NR-302839

2024-09-09 15:35 UTC, paperclypse commented on src/content/docs/query-your-data/explore-query-data/use-charts/chart-refresh-rates.mdx
> +  This option is available to customers on [New Relic's compute usage-based plan](https://newrelic.com/pricing/compute).
@rhetoric101 Is it ok to refer to NR compute like this?

2024-09-09 15:41 UTC, paperclypse commented on src/content/docs/query-your-data/explore-query-data/use-charts/chart-refresh-rates.mdx
> +
```suggestion
```

@nbaenam Based on Rob's info, we need to drop mention of compute for now.

2024-09-09 15:42 UTC, paperclypse requested changes
Once you remove that callout, I think we'll be good to merge this in.

2024-09-10 15:59 UTC, jeff-colucci approved these changes

2024-09-10 16:00 UTC, merged