docs: clarify environment variable and system service relationship for config
newrelic/docs-website pull request #19352
Opened 2024-11-21 11:23 UTC by DavSanchez

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
Clarifies how setting configuration options for the infrastructure-agent with environment variables work with system services.
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
https://newrelic.slack.com/archives/C5A2QGLKT/p1731946333684059

2024-11-25 04:24 UTC, adutta-newrelic requested changes

2024-11-25 08:56 UTC, DavSanchez commented on src/content/docs/infrastructure/infrastructure-agent/configuration/configure-infrastructure-agent.mdx
> +      The way of doing this is platform-dependent, check the documentation for your platform to add environment variables to system services.
I'm mostly suggesting the documentation for the system manager of your platform (if you are on Linux then `systemd` docs, or Windows Services for Windows, etc). I'm adding a clarification.

2024-11-25 08:58 UTC, DavSanchez commented on src/content/docs/infrastructure/infrastructure-agent/configuration/configure-infrastructure-agent.mdx
> +      Often the infrastructure agent will be running as a system service in the host, managed globally (e.g. `systemd` for Linux, Windows Services, `launchd` for macOS, etc).
Done!

2024-11-25 08:58 UTC, DavSanchez commented on src/content/docs/infrastructure/infrastructure-agent/configuration/configure-infrastructure-agent.mdx
> +      To apply configuration changes with environment variables in this setup, these environment variables will need to be set and made visible to the isolated context where the infrastructure agent
Done!

2024-11-25 08:58 UTC, DavSanchez commented on src/content/docs/infrastructure/infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
> +Many of the configuration options listed also admit using environment variables to set values, which will take precendence over the YAML configuration.
Done!

2024-11-25 08:58 UTC, DavSanchez commented on src/content/docs/infrastructure/infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
> +  check the documentation for your platform to add environment variables to system services.
Done!

2024-11-26 04:39 UTC, adutta-newrelic approved these changes
Changes approved.

2024-11-26 05:32 UTC, merged