Chore(user management): Added domain capture reference
newrelic/docs-website pull request #19376
Opened 2024-11-25 15:51 UTC by cbehera-newrelic

* Added call out to reference domain capture feature.
* Ticket: NR-293577

2024-11-26 06:49 UTC, vpayyapilly commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
>  This tutorial will walk you through adding and managing accounts and users.
walks you through the steps to add and manage....

2024-11-26 06:55 UTC, vpayyapilly commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
> +  * For an introduction to our SAML SSO and SCIM offerings, please read [Get started with SSO and SCIM](/docs/accounts/accounts-billing/new-relic-one-user-management/introduction-saml-scim).
replace "please read" with "refer"

2024-11-26 06:56 UTC, vpayyapilly commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
> +  * We recommend that you provision your users with [domain capture](/docs/accounts/accounts-billing/account-setup/domain-capture/), which allows you to automatically add users based on their email d
see my earlier comment

2024-11-26 06:56 UTC, vpayyapilly requested changes
Fix and resubmit.

2024-11-29 05:04 UTC, cbehera-newrelic commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
> +We recommend that you provision your users with [domain capture](/docs/accounts/accounts-billing/account-setup/domain-capture/), which allows you to automatically add users based on their email domai
Made the suggested changes and moved the callout to the "Before you start" section as James had suggested

2024-11-29 05:06 UTC, cbehera-newrelic commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
> +  * For an introduction to our SAML SSO and SCIM offerings, please read [Get started with SSO and SCIM](/docs/accounts/accounts-billing/new-relic-one-user-management/introduction-saml-scim).
done

2024-11-29 05:06 UTC, cbehera-newrelic commented on src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
> +  * We recommend that you provision your users with [domain capture](/docs/accounts/accounts-billing/account-setup/domain-capture/), which allows you to automatically add users based on their email d
fixed

2025-01-06 08:15 UTC, vpayyapilly approved these changes

2025-01-06 08:51 UTC, merged