draft for infra VM
newrelic/docs-website pull request #19447
Opened 2024-12-05 03:12 UTC by cbehera-newrelic

2025-02-13 04:33 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/dev-workflow.mdx
> +* Top 5 vulnerabilities in accordance with the priority rankings
```suggestion
* Top five vulnerabilities in accordance with the priority rankings
```

2025-02-13 04:35 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/infra-workflow.mdx
> +The security summary page for an entity gives you a high level overview of the security of your application or service. Curated dashboards provide you an overall security of your application or servi
```suggestion
The **Security summary** page for an entity gives you a high-level overview of the security of your application or service. Curated dashboards provide you an overall view of the security of your application or service, including:
```

2025-02-13 04:35 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/infra-workflow.mdx
> +* Top 5 vulnerabilities in accordance with the priority rankings
```suggestion
* Top five vulnerabilities in accordance with the priority rankings
```

2025-02-13 04:37 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/infra-workflow.mdx
> +To monitor the health of your infrastructure, use our entity scoped view by navigating to <DNT>**[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities) > Infrastructure > (s
```suggestion
To monitor the health of your infrastructure, use the entity scoped view by navigating to <DNT>**[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities) > Infrastructure > (select an entity) > Security> Summary**</DNT>. For a larger scope, see our document on [managing vulnerabilities as a security team](/docs/vulnerability-management/security-workflow).
```

2025-02-13 04:37 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/infra-workflow.mdx
> +To monitor the health of your infrastructure, use our entity scoped view by navigating to <DNT>**[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities) > Infrastructure > (s
What is the capitalization in the UI for "entity scoped"

2025-02-13 04:38 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/infra-workflow.mdx
> +{/* <img
What benefit is this image bringing to the article?

2025-02-13 04:39 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/overview.mdx
> +metaDescription: Use Security RX to overcome blindspots and remediate vulnerabilities.
```suggestion
metaDescription: Use Security RX to identify blindspots and remediate vulnerabilities.
```

2025-02-13 04:39 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/overview.mdx
> +* Birds-eye view of overall vulnerabilities, including the ones that are detected by New Relic platform and our integration partners such as FOSSA, AWS Security hub, Trivy, Snyk, Dependabot, and othe
```suggestion
* Birds-eye view of overall vulnerabilities, including the ones that are detected by the New Relic platform and our integration partners such as FOSSA, AWS Security hub, Trivy, Snyk, Dependabot, and others.
```

2025-02-13 04:52 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/overview.mdx
> +* Run time visibility of vulnerabilities that your applications or infrastructure may experience (helping you validate if a security patch has been deployed successfully!)
```suggestion
* Run-time visibility of vulnerabilities that your applications or infrastructure may experience (helping you validate whether a security patch has been deployed successfully!)
```

2025-02-13 04:56 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/overview.mdx
> +* Prioritisation feature that helps you assess and address the vulnerabilities those are urgent or matter the most.
```suggestion
* Prioritisation feature that helps you assess and address the urgent or important vulnerabilities.
```

2025-02-13 05:14 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/overview.mdx
> +Thus, you can overcome security blindspots across your entire software application and its associated infrastructure without reducing your team’s efficiency and without getting overwhelmed by the tho
```suggestion
Thus, you can overcome security blindspots across your entire software application and its associated infrastructure without reducing your team’s efficiency and without getting overwhelmed by the 
number of vulnerabilities that your teams may encounter.
```

2025-02-13 05:14 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/overview.mdx
> +        * Identify the most urgent vulnerabilities in my software portfolio
```suggestion
        * Identify the most urgent vulnerabilities in your software portfolio
```

2025-02-13 05:15 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/overview.mdx
> +        * Surface "security" tasks from my security team in my daily workflow so it's easy to deliver more secure software with less toil
```suggestion
        * Surface "security" tasks from the security team in your daily workflow so it's easy to deliver more secure software with less toil
```

2025-02-13 05:15 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/overview.mdx
> +        * Calculate the vulnerability surface area of my software systems
```suggestion
        * Calculate the vulnerability surface area of your software systems
```

2025-02-13 05:17 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/security-workflow-infra.mdx
> +    From the Security RX summary page, select <DNT>**Entities**</DNT> to review the vulnerability status of all your entities. This view shows all your entities and allows you to scan and prioritize
```suggestion
    To review the vulnerability status of all your entities, from the **Security RX summary** page, select <DNT>**Entities**</DNT>. This view shows all your entities and allows you to scan and prioritize vulnerability remediation based on weighted vulnerabilities scores and severity profiles.
```

2025-02-13 05:18 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/security-workflow-infra.mdx
> +    Clicking into an entity opens up a scoped entity view of Vulnerability Management. Learn more about our scoped entity view in our document on [managing vulnerabilities as a developer](/docs/vulne
```suggestion
    Click an entity to open up a **scoped entity** view of Vulnerability Management. Learn more about our scoped entity view in our document on [managing vulnerabilities as a developer](/docs/vulnerability-management/dev-workflow).
```

2025-02-13 05:19 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/security-workflow-infra.mdx
> +    Clicking into an entity opens up a scoped entity view of Vulnerability Management. Learn more about our scoped entity view in our document on [managing vulnerabilities as a developer](/docs/vulne
What is the capitalization for "scoped entity"
Why are we still using "Vulnerability Management" as a proper noun?

2025-02-13 05:19 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/security-workflow-infra.mdx
> +      title="Vulnerability Management overview"
Should this title change?

2025-02-13 05:21 UTC, vpayyapilly requested changes
Stopped reviewing at src/content/docs/vulnerability-management/security-workflow-infra.mdx. 
Why are we still using Vulnerability Management as a proper noun. Check again. Make fixes and resubmit.

2025-02-13 05:33 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/dev-workflow.mdx
> +To monitor the health of specific applications or services, use our entity scoped view by navigating to <DNT>**[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities) > APM &
```suggestion
To monitor the health of specific applications or services, use our entity scoped view by navigating to <DNT>**[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities) > APM & services > (select an entity) > Security > Overview**</DNT>. For a larger scope, refer to our document on [managing vulnerabilities as a security team](/docs/vulnerability-management/security-workflow).
```

2025-02-13 05:36 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/infra-workflow.mdx
> +To monitor the health of specific applications or services, use our entity scoped view by navigating to <DNT>**[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities) > Infra
```suggestion
To monitor the health of specific applications or services, navigate to <DNT>**[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities) > Infrastructure > (select an entity) > Security > Summary**</DNT> and use the **entity scoped** view. For a larger scope, refer to our document on [managing vulnerabilities as a security team](/docs/vulnerability-management/security-workflow).
```

2025-02-13 05:36 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/infra-workflow.mdx
> +To monitor the health of specific applications or services, use our entity scoped view by navigating to <DNT>**[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities) > Infra
What is the capitalization for "entity scoped"

2025-02-13 05:37 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/infra-workflow.mdx
> +<img
What value does this add to the article?

2025-02-13 05:37 UTC, vpayyapilly commented on src/content/docs/vulnerability-management/dev-workflow.mdx
> -<img
What value does this add to the article?

2025-02-13 05:37 UTC, vpayyapilly requested changes
Fix and resubmit.

2025-02-24 22:28 UTC, nickb-newrelic commented on src/content/docs/vulnerability-management/infra-workflow.mdx
> +* Total vulnerabilities
Per Krystle's comments, please replace the screenshot with highlights for each item on this list, numbered.

2026-08-24 17:38 UTC, closed without merging