Whats new 12 06 aws logs
newrelic/docs-website pull request #19466
Opened 2024-12-06 22:03 UTC by jdanna204

Publish Monday Dec 9.2024
No PMM approval needed

2024-12-09 12:30 UTC, Tcohn1 commented on src/content/whats-new/2024/12/whats-new-12-06-AWS-logs.md
> +learnMoreLink: 'https://deploy-preview-19463--docs-website-netlify.netlify.app/install/aws-logs/?service=aws_services'
learnMoreLink: 'https://docs.newrelic.com/install/aws-logs/?service=aws_services'

2024-12-09 12:44 UTC, Tcohn1 commented on src/content/whats-new/2024/12/whats-new-12-06-AWS-logs.md
> +1. [Read our documentation](https://deploy-preview-19463--docs-website-netlify.netlify.app/install/aws-logs/?service=aws_services)
[read our documentation] (https://docs.newrelic.com/install/aws-logs/?service=aws_services)

2024-12-09 14:37 UTC, Tcohn1 commented on src/content/whats-new/2024/12/whats-new-12-06-AWS-logs.md
> +New Relic now supports forwarding logs from AWS services. Our AI-powered log management solution provides instant insights from contextualization with all telemetry data across your entire stack to o
We are thrilled to announce New Relic's latest advancement: one-step observability for AWS, now enhanced with streamlined log forwarding capabilities. Our comprehensive observability solution empowers enterprises by offering seamless integration and enhanced visibility into AWS services within minutes, all within a single user interface.

### Key Benefits of New Relic's Log Forwarding Solution

- **Accelerate Instrumentation:** Set up instrumentation within minutes for forwarding logs and metrics, facilitated by CloudFormation templates and consolidated multi-services onboarding—all accessed through a unified interface.

- **Enhanced Log Management**: Once onboarded, New Relic's Intelligent Observability Platform automatically handles both infrastructure and application performance monitoring, eliminating the need for additional configurations and significantly improving operational efficiency.

- **Improve Operational Efficiency**: Boost your team's operational efficiency while maintaining stringent security and compliance. New Relic's API keys can now be securely stored in AWS Secrets Management, optimizing operations to seamlessly achieve better business outcomes.

- **Reduced Mean Time to Resolution (MTTR)**: New Relic's centralized platform facilitates quick troubleshooting and speeds up incident resolution with a clear view of performance data and relationships across applications, infrastructures, and AWS services out-of-the-box.


###How It Works

1. **Set Up Integration with CloudFormation**: Effortlessly configure AWS integration using the CloudFormation template. Forward metrics and logs by selecting an AWS service and setting up log triggers via S3 or CloudWatch.
2. **Automatic Data Correlation**: Automatically correlate performance data, allowing you to prioritize and address critical issues without the complexity of manual tagging.
3. **Comprehensive Data Querying**: Easily access and analyze log data through the logs UI or New Query Explorer, filtering logs via the Lambda forwarder or Kinesis Data Firehose.

2024-12-09 14:37 UTC, Tcohn1 commented on src/content/whats-new/2024/12/whats-new-12-06-AWS-logs.md
> +To get started:
**Get started today** to achieve a unified, holistic view of your AWS environment, enabling data-driven decision-making while ensuring security and compliance. Discover how New Relic's logs management can boost productivity and help you securely scale your cloud-native applications.

2024-12-09 14:38 UTC, Tcohn1 requested changes
updated language and links

2024-12-12 04:37 UTC, closed without merging

2024-12-12 04:37 UTC, sujitnewrelic commented
Due to build issue, migrated the content to https://github.com/newrelic/docs-website/pull/19487 and merged succesfully. Hence closing this redundant PR.