chore: update workflow & job names
newrelic/docs-website pull request #2751
Opened 2021-06-18 00:23 UTC by nr-kkenney

* updated workflow & job names to better describe what is happening, and better indicate if a particular check can be ignored.

2021-06-18 00:51 UTC, jpvajda requested changes

2021-06-18 00:51 UTC, jpvajda commented on .github/workflows/pr-triage.yml
> +    name: did the pr get added to the docs github board? (optional)
why is this framed as question? 

```suggestion
    name: pr added to the docs github board (optional)
```

2021-06-18 00:51 UTC, jpvajda commented on .github/workflows/pr-triage.yml
> +    name: did the pr get added to the localization github board? (optional)
same feedback

```suggestion
    name: pr added to the localization github board (optional)
```

2021-06-18 00:51 UTC, jpvajda commented on .github/workflows/update-whats-new-ids.yml
> +    name: prepare in-product anncouncements (optional)
```suggestion
    name: generates in-product anncouncements (optional)
```

2021-06-18 00:51 UTC, jpvajda commented on .github/workflows/validate-pr.yml
> +    name: did the docs sites build?
```suggestion
    docs sites build process
```

2021-06-18 00:51 UTC, jpvajda commented on .github/workflows/validate-pr.yml
> +    name: did tests succeed?
```suggestion
    name: all tests succeeded
```

2021-06-18 00:51 UTC, jpvajda commented on .github/workflows/validate-pr.yml
> +    name: did the linter succeed?
```suggestion
    name: all linter checks succeeded
```

2021-06-21 15:12 UTC, nr-kkenney commented
@jpvajda feedback came from @paperclypse to frame most of the checks as questions. @paperclypse if you are good with john's suggestions, I can make those changes.

2021-06-21 15:35 UTC, jpvajda commented
@nr-kkenney Thanks for clarifying I'd prefer we follow a declarative approach and just name the jobs as statements as using questions in programming isn't common. cc @paperclypse

2021-06-21 18:49 UTC, jpvajda commented
@nr-kkenney I haven't heard back from @paperclypse but I want to move this forward, so let's go with my suggested edits as this is a more declarative approach.

2021-06-21 21:04 UTC, jpvajda approved these changes
LGTM

2021-06-21 21:18 UTC, merged

2021-06-24 15:43 UTC, paperclypse commented
@jpvajda Just because something isn't common, doesn't mean it shouldn't be done :) But I think it's fine in this case. Anything is an improvement over what we had, basically. Thanks!