Updating logs pipeline diagram
newrelic/docs-website pull request #2775
Opened 2021-06-21 23:27 UTC by kaileyhaynes

Colorized and updated the logs pipeline diagram to be dark-mode friendly, show what is the customer data, and separate the line between log forwarder and log backend.

2021-06-22 09:59 UTC, urbiz-nr commented on src/content/docs/logs/log-management/ui-data/drop-data-drop-filter-rules.mdx
> +  During the ingestion process, customer log data can be parsed, transformed, or dropped before stored to New Relic's database.
Stored in...

2021-06-22 10:01 UTC, urbiz-nr submitted a review, later dismissed
Nice diagram! Left a comment, up to you!

2021-06-24 18:50 UTC, paperclypse commented
I think the diagram looks fantastic, but it looks like the image is running into the sidebar. Maybe because it's an SVG image?

<img width="1339" alt="Screen Shot 2021-06-24 at 11 33 28 AM" src="https://user-images.githubusercontent.com/7992384/123316938-4cbbb700-d4e2-11eb-9eb0-0edd1772c712.png">

2021-06-24 20:18 UTC, paperclypse submitted a review, later dismissed
Ready to merge in once you decide what to do about the image :)

2021-06-25 00:03 UTC, kaileyhaynes commented
@paperclypse I'll merge when either you or another confirms that it works with the png :)

2021-06-25 07:37 UTC, urbiz-nr commented on src/content/docs/logs/log-management/ui-data/drop-data-drop-filter-rules.mdx
> +  During the ingestion process, customer log data can be parsed, transformed, or dropped before stored in New Relic's database.
"Being" is missing - "... dropped before being stored in NR's database".

2021-06-25 07:44 UTC, urbiz-nr commented
Diagram looks good to me.

2021-06-25 07:44 UTC, urbiz-nr requested changes
Please check comment.

2021-06-25 16:07 UTC, paperclypse approved these changes
Looks good to me!

2021-06-25 16:09 UTC, merged