Doc 6837 publish confirmed docs
newrelic/docs-website pull request #2899
Opened 2021-06-30 22:44 UTC by dbarnesbrownNR

Publish on some recently confirmed docs that have been finished for a while.

2021-07-01 10:42 UTC, urbiz-nr commented on src/content/docs/integrations/prometheus-integrations/install-configure/remote-write-data-drop.mdx
> +This tells Prometheus that you want to do some action against metrics with these labels. To limit which metrics with these labels are affected you must include some value for regex. By default this v
2nd line - "so it will include"

2021-07-01 10:42 UTC, urbiz-nr commented on src/content/docs/integrations/prometheus-integrations/install-configure/remote-write-data-drop.mdx
> +### Example
Header link

2021-07-01 10:42 UTC, urbiz-nr commented on src/content/docs/integrations/prometheus-integrations/install-configure/remote-write-data-drop.mdx
> +### Example
Header link

2021-07-01 10:43 UTC, urbiz-nr commented on src/content/docs/integrations/prometheus-integrations/install-configure/remote-write-data-drop.mdx
> +There are advantages to both dropping data using the method described on this page and using using [NerdGraph](/docs/accounts/accounts/data-management/drop-data-using-nerdgraph/). This section is int
Using is repeated

2021-07-01 10:44 UTC, urbiz-nr commented on src/content/docs/integrations/prometheus-integrations/install-configure/remote-write-data-drop.mdx
> +- - Served must be be accessed at port with path `/-/reload` (assuming the server has lifecycle management enabled as described here in the Prometheus [configuration](https://prometheus.io/docs/prome
Be is duplicated

2021-07-01 10:45 UTC, urbiz-nr commented on src/content/docs/integrations/prometheus-integrations/install-configure/remote-write-data-drop.mdx
> +- - Served must be be accessed at port with path `/-/reload` (assuming the server has lifecycle management enabled as described here in the Prometheus [configuration](https://prometheus.io/docs/prome
Server, not served

2021-07-01 10:45 UTC, urbiz-nr commented on src/content/docs/integrations/prometheus-integrations/install-configure/remote-write-data-drop.mdx
> +- - Served must be be accessed at port with path `/-/reload` (assuming the server has lifecycle management enabled as described here in the Prometheus [configuration](https://prometheus.io/docs/prome
Remove dot at the end

2021-07-01 10:45 UTC, urbiz-nr commented on src/content/docs/integrations/prometheus-integrations/install-configure/remote-write-data-drop.mdx
> +### Considerations for NerdGraph data droping
Header link

2021-07-01 10:46 UTC, urbiz-nr requested changes
Nice! Please check my comments!

2021-07-03 03:29 UTC, dbarnesbrownNR commented
This is one of the borked PRs with merge conflict issues, closing this in favor of the one without.

2021-07-03 03:29 UTC, closed without merging