Android agent v6.3.0 & v6.3.1 release notes
newrelic/docs-website pull request #4372
Opened 2021-10-18 17:45 UTC by ywang-nr

What problems does this PR solve? - Android agent release notes

2021-10-18 20:28 UTC, cthomas-newrelic requested changes

2021-10-18 20:28 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-630.mdx
> +* Resolved missing Retrofit2/OkHttp3 'bytesReceived' and error response bodies results
'response body` (my bad)

2021-10-18 20:28 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-630.mdx
> +* Resolved missing OkHttp3 response bodies that made it incompatible with Mapquest
`made it` -> `made the agent`

2021-10-18 20:36 UTC, ywang-nr commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-630.mdx
> +* Resolved missing Retrofit2/OkHttp3 'bytesReceived' and error response bodies results
done

2021-10-19 16:30 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-630.mdx
> +This release is invalid and should not be used. Please use android agent version 6.3.1.
Capitalize 'Android' and provide link to 6.3.1 release notes

2021-10-19 19:16 UTC, barbnewrelic approved these changes
By adding the releaseDate to the front matter, this seems to have solved the failing build.

2021-10-19 19:16 UTC, merged