style(GPC logs): Style guide edits
newrelic/docs-website pull request #4985
Opened 2021-11-19 19:36 UTC by barbnewrelic

WIP: Update google-cloud-platform-log-forwarding, move headerless section into a collapser

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

2021-11-22 23:44 UTC, mmfred requested changes
@barbnewrelic a few small things.

2021-11-22 23:44 UTC, mmfred commented on src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx
> +        * Reduces the number of API calls and allows to reduce your quota usage.
```suggestion
        * Reduces the number of API calls and allows you to reduce your quota usage.
```

2021-11-22 23:44 UTC, mmfred commented on src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx
> +  Next you will create the GCP Pub/Sub topic that your ingest URL will use.
```suggestion
  Next you'll create the GCP Pub/Sub topic that your ingest URL will use.
```

2021-11-22 23:44 UTC, mmfred commented on src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx
> +* [Apache Maven 3.2 or higher](https://maven.apache.org/). Earlier versions have been observed to fail during the compilation process.
```suggestion
* [Apache Maven 3.2 or higher](https://maven.apache.org/). We've seen earlier versions fail during the compilation process.
```

2021-11-22 23:44 UTC, mmfred commented on src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx
> +  2. Enter the created directory to execute the following commands:
commands or command? Looks like just one.

2021-11-22 23:44 UTC, mmfred commented on src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx
> +          New Relic's Log API url. This should be routable from the VPC in which the Dataflow pipeline runs.
```suggestion
          New Relic's Log API URL. This should be routable from the VPC in which the Dataflow pipeline runs.
```

2021-11-22 23:44 UTC, mmfred commented on src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx
> +          Maximum number of log records to aggregate into a batch before sending them to NewRelic in a single HTTP POST request.
```suggestion
          Maximum number of log records to aggregate into a batch before sending them to New Relic in a single HTTP POST request.
```

2021-11-22 23:44 UTC, mmfred commented on src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx
> +  <table>
Consider expanding the column width for that first column in the following table - some of the parameter names are pretty smushed, and the descriptions will more easily wrap.

2021-11-23 16:23 UTC, barbnewrelic commented
PR review suggestions incorporated. Merging this PR

2021-11-23 16:24 UTC, merged