[Mobile-7423] Android Agent v6.4.1 release notes
newrelic/docs-website pull request #5780
Opened 2022-01-24 21:40 UTC by ywang-nr

* What problems does this PR solve? - release notes for android agent v6.4.1

2022-01-24 21:41 UTC, ywang-nr commented
@cthomas-newrelic for review

2022-01-25 20:48 UTC, cthomas-newrelic requested changes

2022-01-25 20:48 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-641.mdx
> +  Detailed message: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/crypto/tink/daead/AesSivKeyManager
Since this crash could apply to any class, remove ": _Failed resolution of: Lcom/google/crypto/tink/daead/AesSivKeyManager_"

2022-01-26 01:02 UTC, cthomas-newrelic approved these changes
🚢 it.

2022-01-26 01:02 UTC, cthomas-newrelic commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-641.mdx
> +<Callout variant="important">
Sweet!

2022-01-27 18:28 UTC, paperclypse commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-641.mdx
> +* Resolved an error when transform some libraries during build time.
```suggestion
* Resolved an error when transforming some libraries during build time.
```

2022-01-27 18:30 UTC, paperclypse approved these changes

2022-01-27 20:04 UTC, merged