Create troubleshooting article for lock contention in .NET Framework applications
newrelic/docs-website pull request #6778
Opened 2022-03-25 01:26 UTC by JcolemanNR

**Do not merge until we have released the associated version of the .NET Agent**

Creates a new article of interest for customers .NET Agent customers experiencing high lock contention in instrumented applications.

2022-03-25 17:04 UTC, JcolemanNR commented on src/content/docs/apm/agents/net-agent/troubleshooting/lock-contention-appdomain-getdata.mdx
> +(TODO: How should customers contact us?)
@elucus: What should I put in here for this?

2022-03-29 13:46 UTC, angelatan2 requested changes

2022-03-29 13:46 UTC, angelatan2 commented on src/content/docs/apm/agents/net-agent/troubleshooting/lock-contention-appdomain-getdata.mdx
> +When the .NET agent is attached to high throughput **.NET Framework** applications, some customers have reported that thread lock contention can increase dramatically to a point that the application
Please reword:
some customers have reported that thread lock contention can increase dramatically to a point that the application becomes non-responsive.
**to**
a few customers reported observing high thread contention.  Upon  reviewing the process dumps and stack traces, many threads may be blocked by calls to AppDomain.GetData( ).

2022-03-29 16:51 UTC, angelatan2 submitted a review, later dismissed

2022-03-29 21:56 UTC, barbnewrelic commented
@JcolemanNR  Looks great! I made some very minor styleguide edits in your PR, also added it to the taxonomy so it will be visible when published. But I did have a question: This refers to v9.7 but I am not seeing a release note for 9.7. Is this right, or do we need to hold on publishing this until v9.7 is released? Thanks for confirming!

2022-03-29 22:00 UTC, JcolemanNR commented
Hello @barbnewrelic, thanks for making the modifications! 

We had originally planned to release version 9.7 today, but have moved that Monday 4/4/2022. It would be great if we could time the release of this article with that.

2022-03-29 22:08 UTC, barbnewrelic commented
@JcolemanNR Thanks for confirming! I had heard about that delay but just wanted to double check in case this piece might need to go out ahead of time. I will keep your PR with other related PRs for .NET 9.7 release so everything goes together. Thanks again for creating a helpful troubleshooting doc!

2022-04-04 13:37 UTC, barbnewrelic approved these changes
Will publish with .NET agent release

2022-04-04 21:43 UTC, barbnewrelic approved these changes
.NET release is ready, I'll include this with those other docs!

2022-04-04 21:44 UTC, merged