Add instructions for upgrading Windows integrations
newrelic/docs-website pull request #7134
Opened 2022-04-15 22:43 UTC by rhetoric101

We had an old CSAT comment asking why we didn't have upgrade steps for Windows integrations.

2022-04-19 09:31 UTC, paologallinaharbur commented on src/content/docs/infrastructure/host-integrations/installation/update-infrastructure-host-integration-package.mdx
> +### Microsoft SQL Server monitoring integration [#ms-sqlserver]
There are [multiple integrations](http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/infrastructure_agent/windows/integrations/) for windows. 

We(coreint) support:
```
nri-apache/                                                                      -
nri-cassandra/                                                                   -
nri-consul/                                                                      -
nri-couchbase/                                                                   -
nri-elasticsearch/                                                               -
nri-f5/                                                                          -
nri-haproxy/                                                                     -
nri-kafka/                                                                       -
nri-memcached/                                                                   -
nri-mongodb/                                                                     -
nri-mssql/                                                                       -
nri-mysql/                                                                       -
nri-nagios/                                                                      -
nri-nginx/                                                                       -
nri-postgresql/                                                                  -
nri-rabbitmq/                                                                    -
nri-redis/                                                                       -
nri-varnish/                                                                     -
nri-vsphere/                                                                     -
```

Caos supports, however the upgrade process should be exactly the same
```
nri-jmx/                                                                         -
nri-snmp/                                                                        -
nrjmx/    
```

I am not sure about `nri-winpkg`

2022-06-14 17:50 UTC, carlossscastro requested changes

2022-06-14 17:50 UTC, carlossscastro commented on src/content/docs/infrastructure/host-integrations/installation/update-infrastructure-host-integration-package.mdx
> +    3. Change `C:\Program Files\New Relic\newrelic-infra\integrations.d\integration-name-config.yml.sample` to `integration-name-config.yml`, and edit according to your needs.
This step 3 can be removed. This is only needed for a first install. When updating the installer will keep the existing `integration-name-config.yml` file

2022-06-14 17:50 UTC, carlossscastro commented on src/content/docs/infrastructure/host-integrations/installation/update-infrastructure-host-integration-package.mdx
On this section we can add the command to check the package version on a windows server.


On a PowerShell window run the following command to check the version installed:

```
get-package -name "*INTEGRATION_FILE_NAME*" | select name, version
```

mssql integration for example:
```
get-package -name "*nri-mssql*" | select name, version
```

2022-06-14 17:50 UTC, carlossscastro commented on src/content/docs/infrastructure/host-integrations/installation/update-infrastructure-host-integration-package.mdx
> +### You're running services in orchestrated environments [#orchestrated]
We have no support for windows integrations in orchestrated environments so no further info is needed here.

For linux the links are OK as upgrading is as a new install so they are relevant here.

2022-06-16 21:05 UTC, barbnewrelic approved these changes
This is impressive! Succinct yet comprehensive. Thanks for all your hard work on this!

2022-06-16 21:19 UTC, merged