fix(node agent): update compatibility requirements with newer features
newrelic/docs-website pull request #8346
Opened 2022-07-06 17:22 UTC by jordigh

This closes [#1254 of the node-newrelic repo](https://github.com/newrelic/node-newrelic/issues/1254)

A couple of other updates are also included for other instrumented libraries.

2022-07-06 18:10 UTC, homelessbirds approved these changes

2022-07-06 18:19 UTC, bizob2828 requested changes

2022-07-06 18:19 UTC, bizob2828 commented on src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
> +The Node.js agent instruments the native `http` module. In addition, the popular [undici](https://www.npmjs.com/package/undici) client is also supported.
as mentioned in standup.  currently undici is not generally available.  you must set `feature_flag.undici_instrumentation = true`

2022-07-06 18:19 UTC, bizob2828 commented on src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
> +* [Next.js](https://www.npmjs.com/package/next) 12.0.9 or higher (12.2.0 or higher required for middleware instrumentation)
ooh, good point

2022-07-06 18:19 UTC, bizob2828 commented on src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
> +* The [grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) library is supported for unary, streaming, or bidirectional client calls.
🎉

2022-07-08 17:33 UTC, akristen approved these changes

2022-07-08 17:33 UTC, akristen commented on src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
> +The Node.js agent instruments the native `http` module. In addition, the popular [undici](https://www.npmjs.com/package/undici) client also has experimental support.
```suggestion
The Node.js agent instruments the native `http` module. 

In addition, the popular [undici](https://www.npmjs.com/package/undici) client has experimental support as well. To use undici, be sure to set `feature_flag.undici_instrumentation = true` in the `newrelic.js` [configuration file](/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#methods-and-precedence).
```

2022-07-08 18:08 UTC, akristen approved these changes
Thanks for your help + patience on this! Excited to merge it in

2022-07-08 18:08 UTC, merged