AQM Rebuild
newrelic/docs-website pull request #8386
Opened 2022-07-08 17:00 UTC by AlecIsaacson

** Preview Only **

This is a rebuild of the AQM content to reflect the new alert architecture and the NrAiIncident event type.

** Preview Only **

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

2022-07-08 18:09 UTC, a-james-faria commented
@AlecIsaacson - two old KPIs `% ack` and `MTTI` were left in the definitions.

2022-07-08 18:19 UTC, a-james-faria requested changes
Look like some old KPI text was reinserted and some other text was missed.

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
> +* Communicate that the incident details "Acknowledge" feature helps measure meaningful and actionable alerts. See [percentage incident acknowledge KPI](#kpi-user-engagement).
Looks like you tried to delete this but it was reinserted.

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
> +You should measure the value of an incident by the amount of attention it receives. Here, we measure engagement by whether or not an incident has been acknowledged.
old kpi

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
>      title="Percentage acknowledged KPI"
old kpi

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
> +Incidents acknowledged identifies the percentage of incidents that have been engaged with by having their acknowledgement flag set to true. Typically you should compare the current and previous weeks
looks like it was reinserted

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
> +Mean time to investigate identifies the average time it takes for an incident to be acknowledged. Typically you should compare the current and previous weeks.
looks like it was reinserted

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
>  * If the incident alert is always on, do not close or acknowledge it. For further details, see [Second enablement session](#perform-enablement-two).
old kpi verbiage

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
> +The process of measuring alert engagement requires at least two weeks of data before it can proceed. During this time, you should periodically check to see if incident responders are following the al
old kpi verbiage

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
>      title="Mean time to investigate (MTTI) KPI"
old kpi

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
>  * % of incidents investigated
old kpi

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
>  * Improve percent investigated and mean-time-to-investigate KPIs by communicating their importance in improving detection and response times.
old kpi reference

2022-07-08 18:19 UTC, a-james-faria commented on src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
>  * If you look at an alert and decide to take any sort of further investigative action, acknowledge the alert.
old kpi reference

2022-07-26 17:24 UTC, homelessbirds approved these changes

2022-07-27 14:22 UTC, merged