framework updates
newrelic/docs-website pull request #8903
Opened 2022-08-18 20:31 UTC by akristen

Expanding framework support for our agents. This adds the first set of integrations to the docs. I'm also experimenting with restructuring some of these docs while I'm over here

2022-08-18 22:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=8903) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=8903) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=8903) it.</sub>

2022-08-20 02:34 UTC, akristen commented on src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
> +    title="TyperScript"
```suggestion
    title="TypeScript"
```

2022-08-22 15:55 UTC, paperclypse requested changes
@akristen I left you some feedback on CodeStream. Once you make those changes, this is ready to go.

2022-08-22 20:27 UTC, paperclypse commented on src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
> +    title="Supported Node.js frameworks"
This collapser should be swapped with the one after it.

2022-08-22 20:28 UTC, paperclypse submitted a review, later dismissed
Those collapsers feel so much better alphabetized, thanks! There's just one you missed, but I'm approving this one, because I assume you'll take care of it :)

2022-08-22 21:01 UTC, merged