"Whats New": Data Plus - Longer Running Queries
newrelic/docs-website pull request #8998
Opened 2022-08-25 08:39 UTC by emoryzhao

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* This resolves problems with queries timing out for large data volumes of larger systems or services.
* This is release on 08-25-2022 for Data Plus customers.
* The longer running queries extends query durations up 2x (2minutes) for normal NRQL queries and 10x (10 minutes) for asynchronous queries
* If your issue relates to an existing GitHub issue, please link to it.

2022-08-25 08:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/docs-website?pullRequest=8998) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/docs-website?pullRequest=8998) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/docs-website?pullRequest=8998) it.</sub>

2022-08-25 16:46 UTC, zuluecho9 commented
could we find a way to include a link to the data plus docs somewhere? https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing

2022-08-25 17:33 UTC, aalfano7 requested changes
My suggestions: 

- Remove learnMoreLink:
- I think having the NRQL tutorial linked in getStartedLink is misleading, since longer queries are only enabled for Data Plus users. I would change this link to https://newrelic.com/blog/nerdlog/data-plus-pricing
- Make the title action-based: "Analyze larger volumes of data with longer running queries"
- Add comma and change "2" "to" "two" in this sentence: "Data Plus customers get a max query duration of up to 10 minutes via asynchronous queries and up to two minutes via regular NRQL queries, compared to 60 seconds for the existing data option."
- Remove "maximum duration" from and add hyphen to this sentence: "In addition to more powerful and 10x longer-running queries, Data Plus also includes:"
- Should we remove the "Next Steps" CTA in-app? (They already have an account)

2022-08-25 22:16 UTC, emoryzhao commented
> My suggestions:
> 
> * Remove learnMoreLink:
> * I think having the NRQL tutorial linked in getStartedLink is misleading, since longer queries are only enabled for Data Plus users. I would change this link to https://newrelic.com/blog/nerdlog/data-plus-pricing
> * Make the title action-based: "Analyze larger volumes of data with longer running queries"
> * Add comma and change "2" "to" "two" in this sentence: "Data Plus customers get a max query duration of up to 10 minutes via asynchronous queries and up to two minutes via regular NRQL queries, compared to 60 seconds for the existing data option."
> * Remove "maximum duration" from and add hyphen to this sentence: "In addition to more powerful and 10x longer-running queries, Data Plus also includes:"
> * Should we remove the "Next Steps" CTA in-app? (They already have an account)

2022-08-26 22:03 UTC, bradleycamacho approved these changes

2022-08-26 22:06 UTC, merged