[NR-24565] Android Agent 6.9.0 release notes & new app launch time doc
newrelic/docs-website pull request #9286
Opened 2022-09-14 20:40 UTC by ywang-nr

* What problems does this PR solve? - new feature doc, android agent 6.9.0 release notes

Android agent is going to support for reporting app launch time (cold time and hot time only).
Nav: Mobile monitoring --> android agent --> install and config section

Along with a new android release 6.9.0

2022-09-19 21:03 UTC, ywang-nr commented
@cthomas-newrelic for review

2022-09-22 21:12 UTC, zuluecho9 submitted a review, later dismissed

2022-09-22 22:49 UTC, ywang-nr commented
Target release date: 9/27 in the afternoon

2022-09-27 21:43 UTC, cthomas-newrelic requested changes

2022-09-27 21:54 UTC, ywang-nr commented on src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-app-launch-time-android-apps.mdx
> +   <provider
yes, will do.

2022-09-27 22:07 UTC, ywang-nr commented on src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-690.mdx
> +* Add support for reporting app launch time, including cold time and hot time
okay, will do

2022-09-27 22:17 UTC, ywang-nr commented on src/content/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api/android-agent-configuration-feature-flags.mdx
> +    Enable or disable reporting app launch time (cold and hot time) to the [MobileRequest](/docs/insights/nrql-new-relic-query-language/nrql-query-examples/insights-query-examples-new-relic-mobile#mo
corrected to metrics and add more details for the definition

2022-09-28 15:26 UTC, cthomas-newrelic approved these changes
LGTM! Please have docs folks go over it for clarity

2022-09-28 15:30 UTC, ywang-nr commented
Ready for merge and release on 9/28(today)

2022-09-28 16:44 UTC, homelessbirds approved these changes

2022-09-28 16:44 UTC, merged

2022-09-28 16:44 UTC, homelessbirds commented
This looks great-- thank you!