feat(install): added new feedback form to a bunch of installation docs
newrelic/docs-website pull request #9475
Opened 2022-09-26 21:25 UTC by paperclypse

I've added the new feedback form to a bunch of install docs.

2022-09-26 21:31 UTC, roadlittledawn commented
for this to work we'd need to merge this branch into `develop` first

https://github.com/newrelic/docs-website/tree/feat/java-install-ui

2022-09-26 21:31 UTC, roadlittledawn requested changes
did we merge https://github.com/newrelic/docs-website/tree/feat/java-install-ui first?

2022-09-27 20:16 UTC, zuluecho9 approved these changes

2022-09-27 20:20 UTC, paperclypse commented
@roadlittledawn we merged the feature branch in first. Is there something you need to do to bypass the branch protection?

2022-09-27 20:26 UTC, merged